// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.1
// source: notch/dotshake/v1/organization.proto

package organization

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PermissionType int32

const (
	PermissionType_RWXKey PermissionType = 0
	PermissionType_RWKey  PermissionType = 1
	PermissionType_RKey   PermissionType = 2
)

// Enum value maps for PermissionType.
var (
	PermissionType_name = map[int32]string{
		0: "RWXKey",
		1: "RWKey",
		2: "RKey",
	}
	PermissionType_value = map[string]int32{
		"RWXKey": 0,
		"RWKey":  1,
		"RKey":   2,
	}
)

func (x PermissionType) Enum() *PermissionType {
	p := new(PermissionType)
	*p = x
	return p
}

func (x PermissionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PermissionType) Descriptor() protoreflect.EnumDescriptor {
	return file_notch_dotshake_v1_organization_proto_enumTypes[0].Descriptor()
}

func (PermissionType) Type() protoreflect.EnumType {
	return &file_notch_dotshake_v1_organization_proto_enumTypes[0]
}

func (x PermissionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PermissionType.Descriptor instead.
func (PermissionType) EnumDescriptor() ([]byte, []int) {
	return file_notch_dotshake_v1_organization_proto_rawDescGZIP(), []int{0}
}

type GetRequiredForCreateSetupKeyInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrgID string `protobuf:"bytes,1,opt,name=orgID,proto3" json:"orgID,omitempty"`
}

func (x *GetRequiredForCreateSetupKeyInfoRequest) Reset() {
	*x = GetRequiredForCreateSetupKeyInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notch_dotshake_v1_organization_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequiredForCreateSetupKeyInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequiredForCreateSetupKeyInfoRequest) ProtoMessage() {}

func (x *GetRequiredForCreateSetupKeyInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notch_dotshake_v1_organization_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequiredForCreateSetupKeyInfoRequest.ProtoReflect.Descriptor instead.
func (*GetRequiredForCreateSetupKeyInfoRequest) Descriptor() ([]byte, []int) {
	return file_notch_dotshake_v1_organization_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequiredForCreateSetupKeyInfoRequest) GetOrgID() string {
	if x != nil {
		return x.OrgID
	}
	return ""
}

type GetRequiredForCreateSetupKeyInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserGroupID uint64 `protobuf:"varint,1,opt,name=userGroupID,proto3" json:"userGroupID,omitempty"`
	OrgID       string `protobuf:"bytes,2,opt,name=orgID,proto3" json:"orgID,omitempty"`
	NetworkID   uint64 `protobuf:"varint,3,opt,name=networkID,proto3" json:"networkID,omitempty"`
	JobID       uint64 `protobuf:"varint,4,opt,name=jobID,proto3" json:"jobID,omitempty"`
	RoleID      uint64 `protobuf:"varint,5,opt,name=roleID,proto3" json:"roleID,omitempty"`
}

func (x *GetRequiredForCreateSetupKeyInfoResponse) Reset() {
	*x = GetRequiredForCreateSetupKeyInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notch_dotshake_v1_organization_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequiredForCreateSetupKeyInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequiredForCreateSetupKeyInfoResponse) ProtoMessage() {}

func (x *GetRequiredForCreateSetupKeyInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notch_dotshake_v1_organization_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequiredForCreateSetupKeyInfoResponse.ProtoReflect.Descriptor instead.
func (*GetRequiredForCreateSetupKeyInfoResponse) Descriptor() ([]byte, []int) {
	return file_notch_dotshake_v1_organization_proto_rawDescGZIP(), []int{1}
}

func (x *GetRequiredForCreateSetupKeyInfoResponse) GetUserGroupID() uint64 {
	if x != nil {
		return x.UserGroupID
	}
	return 0
}

func (x *GetRequiredForCreateSetupKeyInfoResponse) GetOrgID() string {
	if x != nil {
		return x.OrgID
	}
	return ""
}

func (x *GetRequiredForCreateSetupKeyInfoResponse) GetNetworkID() uint64 {
	if x != nil {
		return x.NetworkID
	}
	return 0
}

func (x *GetRequiredForCreateSetupKeyInfoResponse) GetJobID() uint64 {
	if x != nil {
		return x.JobID
	}
	return 0
}

func (x *GetRequiredForCreateSetupKeyInfoResponse) GetRoleID() uint64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

type CreateSetupKeyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserGroupID uint64 `protobuf:"varint,1,opt,name=userGroupID,proto3" json:"userGroupID,omitempty"`
	OrgGroupID  string `protobuf:"bytes,2,opt,name=orgGroupID,proto3" json:"orgGroupID,omitempty"`
	NetworkID   uint64 `protobuf:"varint,3,opt,name=networkID,proto3" json:"networkID,omitempty"`
	JobID       uint64 `protobuf:"varint,4,opt,name=jobID,proto3" json:"jobID,omitempty"`
	RoleID      uint64 `protobuf:"varint,5,opt,name=roleID,proto3" json:"roleID,omitempty"`
	Email       string `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *CreateSetupKeyRequest) Reset() {
	*x = CreateSetupKeyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notch_dotshake_v1_organization_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSetupKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSetupKeyRequest) ProtoMessage() {}

func (x *CreateSetupKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notch_dotshake_v1_organization_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSetupKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateSetupKeyRequest) Descriptor() ([]byte, []int) {
	return file_notch_dotshake_v1_organization_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSetupKeyRequest) GetUserGroupID() uint64 {
	if x != nil {
		return x.UserGroupID
	}
	return 0
}

func (x *CreateSetupKeyRequest) GetOrgGroupID() string {
	if x != nil {
		return x.OrgGroupID
	}
	return ""
}

func (x *CreateSetupKeyRequest) GetNetworkID() uint64 {
	if x != nil {
		return x.NetworkID
	}
	return 0
}

func (x *CreateSetupKeyRequest) GetJobID() uint64 {
	if x != nil {
		return x.JobID
	}
	return 0
}

func (x *CreateSetupKeyRequest) GetRoleID() uint64 {
	if x != nil {
		return x.RoleID
	}
	return 0
}

func (x *CreateSetupKeyRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type CreateSetupKeyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SetupKey string `protobuf:"bytes,1,opt,name=setupKey,proto3" json:"setupKey,omitempty"`
}

func (x *CreateSetupKeyResponse) Reset() {
	*x = CreateSetupKeyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notch_dotshake_v1_organization_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSetupKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSetupKeyResponse) ProtoMessage() {}

func (x *CreateSetupKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notch_dotshake_v1_organization_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSetupKeyResponse.ProtoReflect.Descriptor instead.
func (*CreateSetupKeyResponse) Descriptor() ([]byte, []int) {
	return file_notch_dotshake_v1_organization_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSetupKeyResponse) GetSetupKey() string {
	if x != nil {
		return x.SetupKey
	}
	return ""
}

var File_notch_dotshake_v1_organization_proto protoreflect.FileDescriptor

var file_notch_dotshake_v1_organization_proto_rawDesc = []byte{
	0x0a, 0x24, 0x6e, 0x6f, 0x74, 0x63, 0x68, 0x2f, 0x64, 0x6f, 0x74, 0x73, 0x68, 0x61, 0x6b, 0x65,
	0x2f, 0x76, 0x31, 0x2f, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x22, 0x3f,
	0x0a, 0x27, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x46, 0x6f, 0x72,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x74, 0x75, 0x70, 0x4b, 0x65, 0x79, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x67,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x44, 0x22,
	0xae, 0x01, 0x0a, 0x28, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x46,
	0x6f, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x74, 0x75, 0x70, 0x4b, 0x65, 0x79,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x75, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x12, 0x14,
	0x0a, 0x05, 0x6f, 0x72, 0x67, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f,
	0x72, 0x67, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49,
	0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65,
	0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x44,
	0x22, 0xbb, 0x01, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x74, 0x75, 0x70,
	0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x75, 0x73,
	0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0b, 0x75, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a,
	0x6f, 0x72, 0x67, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x6f, 0x72, 0x67, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09,
	0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x09, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x6a, 0x6f,
	0x62, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x44,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x34,
	0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x74, 0x75, 0x70, 0x4b, 0x65, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x74, 0x75,
	0x70, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x74, 0x75,
	0x70, 0x4b, 0x65, 0x79, 0x2a, 0x31, 0x0a, 0x0e, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x57, 0x58, 0x4b, 0x65, 0x79,
	0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x57, 0x4b, 0x65, 0x79, 0x10, 0x01, 0x12, 0x08, 0x0a,
	0x04, 0x52, 0x4b, 0x65, 0x79, 0x10, 0x02, 0x32, 0xf2, 0x01, 0x0a, 0x13, 0x4f, 0x72, 0x67, 0x61,
	0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x87, 0x01, 0x0a, 0x20, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x46,
	0x6f, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x74, 0x75, 0x70, 0x4b, 0x65, 0x79,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x46, 0x6f, 0x72, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x53, 0x65, 0x74, 0x75, 0x70, 0x4b, 0x65, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x30, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x46, 0x6f, 0x72, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x53, 0x65, 0x74, 0x75, 0x70, 0x4b, 0x65, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x51, 0x0a, 0x0e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x53, 0x65, 0x74, 0x75, 0x70, 0x4b, 0x65, 0x79, 0x12, 0x1d, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x74, 0x75, 0x70,
	0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x74, 0x75, 0x70, 0x4b,
	0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x10, 0x5a, 0x0e,
	0x2e, 0x2f, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_notch_dotshake_v1_organization_proto_rawDescOnce sync.Once
	file_notch_dotshake_v1_organization_proto_rawDescData = file_notch_dotshake_v1_organization_proto_rawDesc
)

func file_notch_dotshake_v1_organization_proto_rawDescGZIP() []byte {
	file_notch_dotshake_v1_organization_proto_rawDescOnce.Do(func() {
		file_notch_dotshake_v1_organization_proto_rawDescData = protoimpl.X.CompressGZIP(file_notch_dotshake_v1_organization_proto_rawDescData)
	})
	return file_notch_dotshake_v1_organization_proto_rawDescData
}

var file_notch_dotshake_v1_organization_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_notch_dotshake_v1_organization_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_notch_dotshake_v1_organization_proto_goTypes = []interface{}{
	(PermissionType)(0),                              // 0: protos.PermissionType
	(*GetRequiredForCreateSetupKeyInfoRequest)(nil),  // 1: protos.GetRequiredForCreateSetupKeyInfoRequest
	(*GetRequiredForCreateSetupKeyInfoResponse)(nil), // 2: protos.GetRequiredForCreateSetupKeyInfoResponse
	(*CreateSetupKeyRequest)(nil),                    // 3: protos.CreateSetupKeyRequest
	(*CreateSetupKeyResponse)(nil),                   // 4: protos.CreateSetupKeyResponse
}
var file_notch_dotshake_v1_organization_proto_depIdxs = []int32{
	1, // 0: protos.OrganizationService.GetRequiredForCreateSetupKeyInfo:input_type -> protos.GetRequiredForCreateSetupKeyInfoRequest
	3, // 1: protos.OrganizationService.CreateSetupKey:input_type -> protos.CreateSetupKeyRequest
	2, // 2: protos.OrganizationService.GetRequiredForCreateSetupKeyInfo:output_type -> protos.GetRequiredForCreateSetupKeyInfoResponse
	4, // 3: protos.OrganizationService.CreateSetupKey:output_type -> protos.CreateSetupKeyResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_notch_dotshake_v1_organization_proto_init() }
func file_notch_dotshake_v1_organization_proto_init() {
	if File_notch_dotshake_v1_organization_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_notch_dotshake_v1_organization_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequiredForCreateSetupKeyInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notch_dotshake_v1_organization_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequiredForCreateSetupKeyInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notch_dotshake_v1_organization_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSetupKeyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notch_dotshake_v1_organization_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSetupKeyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_notch_dotshake_v1_organization_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notch_dotshake_v1_organization_proto_goTypes,
		DependencyIndexes: file_notch_dotshake_v1_organization_proto_depIdxs,
		EnumInfos:         file_notch_dotshake_v1_organization_proto_enumTypes,
		MessageInfos:      file_notch_dotshake_v1_organization_proto_msgTypes,
	}.Build()
	File_notch_dotshake_v1_organization_proto = out.File
	file_notch_dotshake_v1_organization_proto_rawDesc = nil
	file_notch_dotshake_v1_organization_proto_goTypes = nil
	file_notch_dotshake_v1_organization_proto_depIdxs = nil
}
