// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v3.20.3
// source: runetale/runetale/v1/admin.proto

/* eslint-disable */

export const protobufPackage = "protos";
