// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v3.20.3
// source: runetale/runetale/v1/hashi.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Timestamp } from "../../../google/protobuf/timestamp";

export const protobufPackage = "protos";

export interface NodePublic {
  /** 32バイト固定長 */
  k: Uint8Array;
}

export interface Endpoint {
  /** net.UDPAddrを文字列で表現 (e.g., "192.168.1.1:51820") */
  addr: string;
  type: number;
}

export interface Status {
  backendState: string;
  /** netip.Addr を文字列として扱う */
  runetaleIps: string[];
  interactiveLoginUrl?: string | undefined;
  self?:
    | PeerStatus
    | undefined;
  /** map[key.NodePublic]*PeerStatus */
  peer: { [key: string]: PeerStatus };
}

export interface Status_PeerEntry {
  key: string;
  value: PeerStatus | undefined;
}

export interface PeerStatus {
  /** runecfg.NodeID を string で表現 */
  id: number;
  publicKey: NodePublic | undefined;
  os: string;
  hostName: string;
  /** netip.Addr を文字列として扱う */
  runetaleIps: string[];
  peerApiUrl: string[];
  /** readonly.Slice[netip.Prefix] を文字列のリストで表現 */
  allowedIps: string[];
  rxBytes: number;
  txBytes: number;
  lastHandshake: Date | undefined;
  lastWrite: Date | undefined;
  addrs: string[];
  curAddr?: string | undefined;
  iceAddr?: string | undefined;
}

export interface UserspacePeerEngineStatus {
  gotAt: Date | undefined;
  peers: CompactPeerStatus[];
  /** []*runecfg.Endpoint */
  localAddrs: Endpoint[];
}

export interface CompactPeerStatus {
  nodeKey: NodePublic | undefined;
  txBytes: number;
  rxBytes: number;
  lastHandshake: Date | undefined;
}

function createBaseNodePublic(): NodePublic {
  return { k: new Uint8Array(0) };
}

export const NodePublic: MessageFns<NodePublic> = {
  encode(message: NodePublic, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.k.length !== 0) {
      writer.uint32(10).bytes(message.k);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NodePublic {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNodePublic();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.k = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NodePublic {
    return { k: isSet(object.k) ? bytesFromBase64(object.k) : new Uint8Array(0) };
  },

  toJSON(message: NodePublic): unknown {
    const obj: any = {};
    if (message.k.length !== 0) {
      obj.k = base64FromBytes(message.k);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NodePublic>, I>>(base?: I): NodePublic {
    return NodePublic.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NodePublic>, I>>(object: I): NodePublic {
    const message = createBaseNodePublic();
    message.k = object.k ?? new Uint8Array(0);
    return message;
  },
};

function createBaseEndpoint(): Endpoint {
  return { addr: "", type: 0 };
}

export const Endpoint: MessageFns<Endpoint> = {
  encode(message: Endpoint, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.addr !== "") {
      writer.uint32(10).string(message.addr);
    }
    if (message.type !== 0) {
      writer.uint32(16).int64(message.type);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Endpoint {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEndpoint();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.addr = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.type = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Endpoint {
    return {
      addr: isSet(object.addr) ? globalThis.String(object.addr) : "",
      type: isSet(object.type) ? globalThis.Number(object.type) : 0,
    };
  },

  toJSON(message: Endpoint): unknown {
    const obj: any = {};
    if (message.addr !== "") {
      obj.addr = message.addr;
    }
    if (message.type !== 0) {
      obj.type = Math.round(message.type);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Endpoint>, I>>(base?: I): Endpoint {
    return Endpoint.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Endpoint>, I>>(object: I): Endpoint {
    const message = createBaseEndpoint();
    message.addr = object.addr ?? "";
    message.type = object.type ?? 0;
    return message;
  },
};

function createBaseStatus(): Status {
  return { backendState: "", runetaleIps: [], interactiveLoginUrl: undefined, self: undefined, peer: {} };
}

export const Status: MessageFns<Status> = {
  encode(message: Status, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.backendState !== "") {
      writer.uint32(10).string(message.backendState);
    }
    for (const v of message.runetaleIps) {
      writer.uint32(18).string(v!);
    }
    if (message.interactiveLoginUrl !== undefined) {
      writer.uint32(26).string(message.interactiveLoginUrl);
    }
    if (message.self !== undefined) {
      PeerStatus.encode(message.self, writer.uint32(34).fork()).join();
    }
    Object.entries(message.peer).forEach(([key, value]) => {
      Status_PeerEntry.encode({ key: key as any, value }, writer.uint32(42).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Status {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStatus();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.backendState = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.runetaleIps.push(reader.string());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.interactiveLoginUrl = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.self = PeerStatus.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          const entry5 = Status_PeerEntry.decode(reader, reader.uint32());
          if (entry5.value !== undefined) {
            message.peer[entry5.key] = entry5.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Status {
    return {
      backendState: isSet(object.backendState) ? globalThis.String(object.backendState) : "",
      runetaleIps: globalThis.Array.isArray(object?.runetaleIps)
        ? object.runetaleIps.map((e: any) => globalThis.String(e))
        : [],
      interactiveLoginUrl: isSet(object.interactiveLoginUrl)
        ? globalThis.String(object.interactiveLoginUrl)
        : undefined,
      self: isSet(object.self) ? PeerStatus.fromJSON(object.self) : undefined,
      peer: isObject(object.peer)
        ? Object.entries(object.peer).reduce<{ [key: string]: PeerStatus }>((acc, [key, value]) => {
          acc[key] = PeerStatus.fromJSON(value);
          return acc;
        }, {})
        : {},
    };
  },

  toJSON(message: Status): unknown {
    const obj: any = {};
    if (message.backendState !== "") {
      obj.backendState = message.backendState;
    }
    if (message.runetaleIps?.length) {
      obj.runetaleIps = message.runetaleIps;
    }
    if (message.interactiveLoginUrl !== undefined) {
      obj.interactiveLoginUrl = message.interactiveLoginUrl;
    }
    if (message.self !== undefined) {
      obj.self = PeerStatus.toJSON(message.self);
    }
    if (message.peer) {
      const entries = Object.entries(message.peer);
      if (entries.length > 0) {
        obj.peer = {};
        entries.forEach(([k, v]) => {
          obj.peer[k] = PeerStatus.toJSON(v);
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Status>, I>>(base?: I): Status {
    return Status.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Status>, I>>(object: I): Status {
    const message = createBaseStatus();
    message.backendState = object.backendState ?? "";
    message.runetaleIps = object.runetaleIps?.map((e) => e) || [];
    message.interactiveLoginUrl = object.interactiveLoginUrl ?? undefined;
    message.self = (object.self !== undefined && object.self !== null)
      ? PeerStatus.fromPartial(object.self)
      : undefined;
    message.peer = Object.entries(object.peer ?? {}).reduce<{ [key: string]: PeerStatus }>((acc, [key, value]) => {
      if (value !== undefined) {
        acc[key] = PeerStatus.fromPartial(value);
      }
      return acc;
    }, {});
    return message;
  },
};

function createBaseStatus_PeerEntry(): Status_PeerEntry {
  return { key: "", value: undefined };
}

export const Status_PeerEntry: MessageFns<Status_PeerEntry> = {
  encode(message: Status_PeerEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== undefined) {
      PeerStatus.encode(message.value, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Status_PeerEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStatus_PeerEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = PeerStatus.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Status_PeerEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? PeerStatus.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: Status_PeerEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== undefined) {
      obj.value = PeerStatus.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Status_PeerEntry>, I>>(base?: I): Status_PeerEntry {
    return Status_PeerEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Status_PeerEntry>, I>>(object: I): Status_PeerEntry {
    const message = createBaseStatus_PeerEntry();
    message.key = object.key ?? "";
    message.value = (object.value !== undefined && object.value !== null)
      ? PeerStatus.fromPartial(object.value)
      : undefined;
    return message;
  },
};

function createBasePeerStatus(): PeerStatus {
  return {
    id: 0,
    publicKey: undefined,
    os: "",
    hostName: "",
    runetaleIps: [],
    peerApiUrl: [],
    allowedIps: [],
    rxBytes: 0,
    txBytes: 0,
    lastHandshake: undefined,
    lastWrite: undefined,
    addrs: [],
    curAddr: undefined,
    iceAddr: undefined,
  };
}

export const PeerStatus: MessageFns<PeerStatus> = {
  encode(message: PeerStatus, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int64(message.id);
    }
    if (message.publicKey !== undefined) {
      NodePublic.encode(message.publicKey, writer.uint32(18).fork()).join();
    }
    if (message.os !== "") {
      writer.uint32(26).string(message.os);
    }
    if (message.hostName !== "") {
      writer.uint32(34).string(message.hostName);
    }
    for (const v of message.runetaleIps) {
      writer.uint32(42).string(v!);
    }
    for (const v of message.peerApiUrl) {
      writer.uint32(50).string(v!);
    }
    for (const v of message.allowedIps) {
      writer.uint32(58).string(v!);
    }
    if (message.rxBytes !== 0) {
      writer.uint32(64).int64(message.rxBytes);
    }
    if (message.txBytes !== 0) {
      writer.uint32(72).int64(message.txBytes);
    }
    if (message.lastHandshake !== undefined) {
      Timestamp.encode(toTimestamp(message.lastHandshake), writer.uint32(82).fork()).join();
    }
    if (message.lastWrite !== undefined) {
      Timestamp.encode(toTimestamp(message.lastWrite), writer.uint32(90).fork()).join();
    }
    for (const v of message.addrs) {
      writer.uint32(98).string(v!);
    }
    if (message.curAddr !== undefined) {
      writer.uint32(106).string(message.curAddr);
    }
    if (message.iceAddr !== undefined) {
      writer.uint32(114).string(message.iceAddr);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PeerStatus {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePeerStatus();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.publicKey = NodePublic.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.os = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.hostName = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.runetaleIps.push(reader.string());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.peerApiUrl.push(reader.string());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.allowedIps.push(reader.string());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.rxBytes = longToNumber(reader.int64());
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.txBytes = longToNumber(reader.int64());
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.lastHandshake = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.lastWrite = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.addrs.push(reader.string());
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.curAddr = reader.string();
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.iceAddr = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PeerStatus {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      publicKey: isSet(object.publicKey) ? NodePublic.fromJSON(object.publicKey) : undefined,
      os: isSet(object.os) ? globalThis.String(object.os) : "",
      hostName: isSet(object.hostName) ? globalThis.String(object.hostName) : "",
      runetaleIps: globalThis.Array.isArray(object?.runetaleIps)
        ? object.runetaleIps.map((e: any) => globalThis.String(e))
        : [],
      peerApiUrl: globalThis.Array.isArray(object?.peerApiUrl)
        ? object.peerApiUrl.map((e: any) => globalThis.String(e))
        : [],
      allowedIps: globalThis.Array.isArray(object?.allowedIps)
        ? object.allowedIps.map((e: any) => globalThis.String(e))
        : [],
      rxBytes: isSet(object.rxBytes) ? globalThis.Number(object.rxBytes) : 0,
      txBytes: isSet(object.txBytes) ? globalThis.Number(object.txBytes) : 0,
      lastHandshake: isSet(object.lastHandshake) ? fromJsonTimestamp(object.lastHandshake) : undefined,
      lastWrite: isSet(object.lastWrite) ? fromJsonTimestamp(object.lastWrite) : undefined,
      addrs: globalThis.Array.isArray(object?.addrs) ? object.addrs.map((e: any) => globalThis.String(e)) : [],
      curAddr: isSet(object.curAddr) ? globalThis.String(object.curAddr) : undefined,
      iceAddr: isSet(object.iceAddr) ? globalThis.String(object.iceAddr) : undefined,
    };
  },

  toJSON(message: PeerStatus): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.publicKey !== undefined) {
      obj.publicKey = NodePublic.toJSON(message.publicKey);
    }
    if (message.os !== "") {
      obj.os = message.os;
    }
    if (message.hostName !== "") {
      obj.hostName = message.hostName;
    }
    if (message.runetaleIps?.length) {
      obj.runetaleIps = message.runetaleIps;
    }
    if (message.peerApiUrl?.length) {
      obj.peerApiUrl = message.peerApiUrl;
    }
    if (message.allowedIps?.length) {
      obj.allowedIps = message.allowedIps;
    }
    if (message.rxBytes !== 0) {
      obj.rxBytes = Math.round(message.rxBytes);
    }
    if (message.txBytes !== 0) {
      obj.txBytes = Math.round(message.txBytes);
    }
    if (message.lastHandshake !== undefined) {
      obj.lastHandshake = message.lastHandshake.toISOString();
    }
    if (message.lastWrite !== undefined) {
      obj.lastWrite = message.lastWrite.toISOString();
    }
    if (message.addrs?.length) {
      obj.addrs = message.addrs;
    }
    if (message.curAddr !== undefined) {
      obj.curAddr = message.curAddr;
    }
    if (message.iceAddr !== undefined) {
      obj.iceAddr = message.iceAddr;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PeerStatus>, I>>(base?: I): PeerStatus {
    return PeerStatus.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PeerStatus>, I>>(object: I): PeerStatus {
    const message = createBasePeerStatus();
    message.id = object.id ?? 0;
    message.publicKey = (object.publicKey !== undefined && object.publicKey !== null)
      ? NodePublic.fromPartial(object.publicKey)
      : undefined;
    message.os = object.os ?? "";
    message.hostName = object.hostName ?? "";
    message.runetaleIps = object.runetaleIps?.map((e) => e) || [];
    message.peerApiUrl = object.peerApiUrl?.map((e) => e) || [];
    message.allowedIps = object.allowedIps?.map((e) => e) || [];
    message.rxBytes = object.rxBytes ?? 0;
    message.txBytes = object.txBytes ?? 0;
    message.lastHandshake = object.lastHandshake ?? undefined;
    message.lastWrite = object.lastWrite ?? undefined;
    message.addrs = object.addrs?.map((e) => e) || [];
    message.curAddr = object.curAddr ?? undefined;
    message.iceAddr = object.iceAddr ?? undefined;
    return message;
  },
};

function createBaseUserspacePeerEngineStatus(): UserspacePeerEngineStatus {
  return { gotAt: undefined, peers: [], localAddrs: [] };
}

export const UserspacePeerEngineStatus: MessageFns<UserspacePeerEngineStatus> = {
  encode(message: UserspacePeerEngineStatus, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.gotAt !== undefined) {
      Timestamp.encode(toTimestamp(message.gotAt), writer.uint32(10).fork()).join();
    }
    for (const v of message.peers) {
      CompactPeerStatus.encode(v!, writer.uint32(18).fork()).join();
    }
    for (const v of message.localAddrs) {
      Endpoint.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserspacePeerEngineStatus {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserspacePeerEngineStatus();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.gotAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.peers.push(CompactPeerStatus.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.localAddrs.push(Endpoint.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserspacePeerEngineStatus {
    return {
      gotAt: isSet(object.gotAt) ? fromJsonTimestamp(object.gotAt) : undefined,
      peers: globalThis.Array.isArray(object?.peers) ? object.peers.map((e: any) => CompactPeerStatus.fromJSON(e)) : [],
      localAddrs: globalThis.Array.isArray(object?.localAddrs)
        ? object.localAddrs.map((e: any) => Endpoint.fromJSON(e))
        : [],
    };
  },

  toJSON(message: UserspacePeerEngineStatus): unknown {
    const obj: any = {};
    if (message.gotAt !== undefined) {
      obj.gotAt = message.gotAt.toISOString();
    }
    if (message.peers?.length) {
      obj.peers = message.peers.map((e) => CompactPeerStatus.toJSON(e));
    }
    if (message.localAddrs?.length) {
      obj.localAddrs = message.localAddrs.map((e) => Endpoint.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserspacePeerEngineStatus>, I>>(base?: I): UserspacePeerEngineStatus {
    return UserspacePeerEngineStatus.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserspacePeerEngineStatus>, I>>(object: I): UserspacePeerEngineStatus {
    const message = createBaseUserspacePeerEngineStatus();
    message.gotAt = object.gotAt ?? undefined;
    message.peers = object.peers?.map((e) => CompactPeerStatus.fromPartial(e)) || [];
    message.localAddrs = object.localAddrs?.map((e) => Endpoint.fromPartial(e)) || [];
    return message;
  },
};

function createBaseCompactPeerStatus(): CompactPeerStatus {
  return { nodeKey: undefined, txBytes: 0, rxBytes: 0, lastHandshake: undefined };
}

export const CompactPeerStatus: MessageFns<CompactPeerStatus> = {
  encode(message: CompactPeerStatus, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.nodeKey !== undefined) {
      NodePublic.encode(message.nodeKey, writer.uint32(10).fork()).join();
    }
    if (message.txBytes !== 0) {
      writer.uint32(16).int64(message.txBytes);
    }
    if (message.rxBytes !== 0) {
      writer.uint32(24).int64(message.rxBytes);
    }
    if (message.lastHandshake !== undefined) {
      Timestamp.encode(toTimestamp(message.lastHandshake), writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CompactPeerStatus {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCompactPeerStatus();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.nodeKey = NodePublic.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.txBytes = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.rxBytes = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.lastHandshake = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CompactPeerStatus {
    return {
      nodeKey: isSet(object.nodeKey) ? NodePublic.fromJSON(object.nodeKey) : undefined,
      txBytes: isSet(object.txBytes) ? globalThis.Number(object.txBytes) : 0,
      rxBytes: isSet(object.rxBytes) ? globalThis.Number(object.rxBytes) : 0,
      lastHandshake: isSet(object.lastHandshake) ? fromJsonTimestamp(object.lastHandshake) : undefined,
    };
  },

  toJSON(message: CompactPeerStatus): unknown {
    const obj: any = {};
    if (message.nodeKey !== undefined) {
      obj.nodeKey = NodePublic.toJSON(message.nodeKey);
    }
    if (message.txBytes !== 0) {
      obj.txBytes = Math.round(message.txBytes);
    }
    if (message.rxBytes !== 0) {
      obj.rxBytes = Math.round(message.rxBytes);
    }
    if (message.lastHandshake !== undefined) {
      obj.lastHandshake = message.lastHandshake.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CompactPeerStatus>, I>>(base?: I): CompactPeerStatus {
    return CompactPeerStatus.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CompactPeerStatus>, I>>(object: I): CompactPeerStatus {
    const message = createBaseCompactPeerStatus();
    message.nodeKey = (object.nodeKey !== undefined && object.nodeKey !== null)
      ? NodePublic.fromPartial(object.nodeKey)
      : undefined;
    message.txBytes = object.txBytes ?? 0;
    message.rxBytes = object.rxBytes ?? 0;
    message.lastHandshake = object.lastHandshake ?? undefined;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
