// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v3.20.3
// source: runetale/runetale/v1/hashi.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { grpc } from "@improbable-eng/grpc-web";
import { BrowserHeaders } from "browser-headers";
import { Empty } from "../../../google/protobuf/empty";
import { Timestamp } from "../../../google/protobuf/timestamp";

export const protobufPackage = "protos";

export interface Endpoint {
  /** net.UDPAddrを文字列で表現 (e.g., "192.168.1.1:51820") */
  addr: string;
  /** "turn" or "stun" from ice_endpoint.go */
  type: string;
}

export interface HashiStatus {
  backendState: string;
  /** netip.Addr を文字列として扱う */
  runetaleIps: string[];
  interactiveLoginUrl: string;
  self?:
    | PeerStatus
    | undefined;
  /** map[key.NodePublic]*PeerStatus */
  peer: { [key: string]: PeerStatus };
}

export interface HashiStatus_PeerEntry {
  key: string;
  value: PeerStatus | undefined;
}

export interface PeerStatus {
  id: number;
  publicKey: string;
  os: string;
  hostName: string;
  /** netip.Addr を文字列として扱う */
  runetaleIps: string[];
  peerApiUrl: string[];
  /** [netip.Prefix] を文字列のリストで表現 */
  allowedIps: string[];
  rxBytes: number;
  txBytes: number;
  lastHandshake: Date | undefined;
  lastWrite: Date | undefined;
  addrs: string[];
  curAddr?: string | undefined;
  iceAddr?: string | undefined;
}

export interface UserspacePeerEngineStatus {
  gotAt: Date | undefined;
  peers: CompactPeerStatus[];
  /** []*runecfg.Endpoint */
  localAddrs: Endpoint[];
}

export interface CompactPeerStatus {
  nodeKey: string;
  txBytes: number;
  rxBytes: number;
  lastHandshake: Date | undefined;
}

/**
 * Hashigo struct like, hashiog(梯子) is a bridge in Japanese.
 * 橋 are essential infrastructure in the world.
 * The same holds true in the world of Runetale.
 * A 橋 serves as the sole common pathway for a node, referenced through the API to enable flexible network configuration within Runetale.
 * There is also a double meaning with "Hashi(お箸, chopstick)" a part of Japanese culture.
 * Like using chopsticks, we carefully pick and fine-tune the settings with precision.
 */
export interface Hashigo {
  serverUrl: string;
  signalUrl: string;
  /** incoming packet all block */
  barricade: boolean;
  /** このノードがAdvertiseするRoutes */
  advertiseRoutes: string[];
  /** Whether to accept routes from subnet linker. Default: on */
  acceptRoutes: boolean;
  /**
   * SNAT を無効にすると、Runetaleのトラフィックをサブネットリレーを
   * ネットワークで追加の手動設定が必要になります。
   * 基本的にはonにしておいてください。
   */
  snatSubnetRoutes: boolean;
  /**
   * linuxのfirewallをstatefulで扱うかどうかを設定します。
   * デフォルトはONです。
   */
  statefulFilter: boolean;
}

export interface PingResult {
  ip: string;
  nodeIp: string;
  nodeName: string;
  err: string;
  latencySeconds: number;
  endpoint: string;
  peerApiPort: number;
  peerApiUrl: string;
  isLocalIp: boolean;
}

export interface ComposeRequest {
  key: string;
}

export interface HashigoRequest {
  barricadeSet: boolean;
  acceptRoutesSet: boolean;
  snatSubnetRoutesSet: boolean;
  statefulFilterSet: boolean;
}

function createBaseEndpoint(): Endpoint {
  return { addr: "", type: "" };
}

export const Endpoint: MessageFns<Endpoint> = {
  encode(message: Endpoint, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.addr !== "") {
      writer.uint32(10).string(message.addr);
    }
    if (message.type !== "") {
      writer.uint32(18).string(message.type);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Endpoint {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEndpoint();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.addr = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.type = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Endpoint {
    return {
      addr: isSet(object.addr) ? globalThis.String(object.addr) : "",
      type: isSet(object.type) ? globalThis.String(object.type) : "",
    };
  },

  toJSON(message: Endpoint): unknown {
    const obj: any = {};
    if (message.addr !== "") {
      obj.addr = message.addr;
    }
    if (message.type !== "") {
      obj.type = message.type;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Endpoint>, I>>(base?: I): Endpoint {
    return Endpoint.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Endpoint>, I>>(object: I): Endpoint {
    const message = createBaseEndpoint();
    message.addr = object.addr ?? "";
    message.type = object.type ?? "";
    return message;
  },
};

function createBaseHashiStatus(): HashiStatus {
  return { backendState: "", runetaleIps: [], interactiveLoginUrl: "", self: undefined, peer: {} };
}

export const HashiStatus: MessageFns<HashiStatus> = {
  encode(message: HashiStatus, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.backendState !== "") {
      writer.uint32(10).string(message.backendState);
    }
    for (const v of message.runetaleIps) {
      writer.uint32(18).string(v!);
    }
    if (message.interactiveLoginUrl !== "") {
      writer.uint32(26).string(message.interactiveLoginUrl);
    }
    if (message.self !== undefined) {
      PeerStatus.encode(message.self, writer.uint32(34).fork()).join();
    }
    Object.entries(message.peer).forEach(([key, value]) => {
      HashiStatus_PeerEntry.encode({ key: key as any, value }, writer.uint32(42).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HashiStatus {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHashiStatus();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.backendState = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.runetaleIps.push(reader.string());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.interactiveLoginUrl = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.self = PeerStatus.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          const entry5 = HashiStatus_PeerEntry.decode(reader, reader.uint32());
          if (entry5.value !== undefined) {
            message.peer[entry5.key] = entry5.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HashiStatus {
    return {
      backendState: isSet(object.backendState) ? globalThis.String(object.backendState) : "",
      runetaleIps: globalThis.Array.isArray(object?.runetaleIps)
        ? object.runetaleIps.map((e: any) => globalThis.String(e))
        : [],
      interactiveLoginUrl: isSet(object.interactiveLoginUrl) ? globalThis.String(object.interactiveLoginUrl) : "",
      self: isSet(object.self) ? PeerStatus.fromJSON(object.self) : undefined,
      peer: isObject(object.peer)
        ? Object.entries(object.peer).reduce<{ [key: string]: PeerStatus }>((acc, [key, value]) => {
          acc[key] = PeerStatus.fromJSON(value);
          return acc;
        }, {})
        : {},
    };
  },

  toJSON(message: HashiStatus): unknown {
    const obj: any = {};
    if (message.backendState !== "") {
      obj.backendState = message.backendState;
    }
    if (message.runetaleIps?.length) {
      obj.runetaleIps = message.runetaleIps;
    }
    if (message.interactiveLoginUrl !== "") {
      obj.interactiveLoginUrl = message.interactiveLoginUrl;
    }
    if (message.self !== undefined) {
      obj.self = PeerStatus.toJSON(message.self);
    }
    if (message.peer) {
      const entries = Object.entries(message.peer);
      if (entries.length > 0) {
        obj.peer = {};
        entries.forEach(([k, v]) => {
          obj.peer[k] = PeerStatus.toJSON(v);
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HashiStatus>, I>>(base?: I): HashiStatus {
    return HashiStatus.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HashiStatus>, I>>(object: I): HashiStatus {
    const message = createBaseHashiStatus();
    message.backendState = object.backendState ?? "";
    message.runetaleIps = object.runetaleIps?.map((e) => e) || [];
    message.interactiveLoginUrl = object.interactiveLoginUrl ?? "";
    message.self = (object.self !== undefined && object.self !== null)
      ? PeerStatus.fromPartial(object.self)
      : undefined;
    message.peer = Object.entries(object.peer ?? {}).reduce<{ [key: string]: PeerStatus }>((acc, [key, value]) => {
      if (value !== undefined) {
        acc[key] = PeerStatus.fromPartial(value);
      }
      return acc;
    }, {});
    return message;
  },
};

function createBaseHashiStatus_PeerEntry(): HashiStatus_PeerEntry {
  return { key: "", value: undefined };
}

export const HashiStatus_PeerEntry: MessageFns<HashiStatus_PeerEntry> = {
  encode(message: HashiStatus_PeerEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== undefined) {
      PeerStatus.encode(message.value, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HashiStatus_PeerEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHashiStatus_PeerEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = PeerStatus.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HashiStatus_PeerEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? PeerStatus.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: HashiStatus_PeerEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== undefined) {
      obj.value = PeerStatus.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HashiStatus_PeerEntry>, I>>(base?: I): HashiStatus_PeerEntry {
    return HashiStatus_PeerEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HashiStatus_PeerEntry>, I>>(object: I): HashiStatus_PeerEntry {
    const message = createBaseHashiStatus_PeerEntry();
    message.key = object.key ?? "";
    message.value = (object.value !== undefined && object.value !== null)
      ? PeerStatus.fromPartial(object.value)
      : undefined;
    return message;
  },
};

function createBasePeerStatus(): PeerStatus {
  return {
    id: 0,
    publicKey: "",
    os: "",
    hostName: "",
    runetaleIps: [],
    peerApiUrl: [],
    allowedIps: [],
    rxBytes: 0,
    txBytes: 0,
    lastHandshake: undefined,
    lastWrite: undefined,
    addrs: [],
    curAddr: undefined,
    iceAddr: undefined,
  };
}

export const PeerStatus: MessageFns<PeerStatus> = {
  encode(message: PeerStatus, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int64(message.id);
    }
    if (message.publicKey !== "") {
      writer.uint32(18).string(message.publicKey);
    }
    if (message.os !== "") {
      writer.uint32(26).string(message.os);
    }
    if (message.hostName !== "") {
      writer.uint32(34).string(message.hostName);
    }
    for (const v of message.runetaleIps) {
      writer.uint32(42).string(v!);
    }
    for (const v of message.peerApiUrl) {
      writer.uint32(50).string(v!);
    }
    for (const v of message.allowedIps) {
      writer.uint32(58).string(v!);
    }
    if (message.rxBytes !== 0) {
      writer.uint32(64).int64(message.rxBytes);
    }
    if (message.txBytes !== 0) {
      writer.uint32(72).int64(message.txBytes);
    }
    if (message.lastHandshake !== undefined) {
      Timestamp.encode(toTimestamp(message.lastHandshake), writer.uint32(82).fork()).join();
    }
    if (message.lastWrite !== undefined) {
      Timestamp.encode(toTimestamp(message.lastWrite), writer.uint32(90).fork()).join();
    }
    for (const v of message.addrs) {
      writer.uint32(98).string(v!);
    }
    if (message.curAddr !== undefined) {
      writer.uint32(106).string(message.curAddr);
    }
    if (message.iceAddr !== undefined) {
      writer.uint32(114).string(message.iceAddr);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PeerStatus {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePeerStatus();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.publicKey = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.os = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.hostName = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.runetaleIps.push(reader.string());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.peerApiUrl.push(reader.string());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.allowedIps.push(reader.string());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.rxBytes = longToNumber(reader.int64());
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.txBytes = longToNumber(reader.int64());
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.lastHandshake = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.lastWrite = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.addrs.push(reader.string());
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.curAddr = reader.string();
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.iceAddr = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PeerStatus {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      publicKey: isSet(object.publicKey) ? globalThis.String(object.publicKey) : "",
      os: isSet(object.os) ? globalThis.String(object.os) : "",
      hostName: isSet(object.hostName) ? globalThis.String(object.hostName) : "",
      runetaleIps: globalThis.Array.isArray(object?.RunetaleIPs)
        ? object.RunetaleIPs.map((e: any) => globalThis.String(e))
        : [],
      peerApiUrl: globalThis.Array.isArray(object?.peerApiUrl)
        ? object.peerApiUrl.map((e: any) => globalThis.String(e))
        : [],
      allowedIps: globalThis.Array.isArray(object?.allowedIps)
        ? object.allowedIps.map((e: any) => globalThis.String(e))
        : [],
      rxBytes: isSet(object.rxBytes) ? globalThis.Number(object.rxBytes) : 0,
      txBytes: isSet(object.txBytes) ? globalThis.Number(object.txBytes) : 0,
      lastHandshake: isSet(object.lastHandshake) ? fromJsonTimestamp(object.lastHandshake) : undefined,
      lastWrite: isSet(object.lastWrite) ? fromJsonTimestamp(object.lastWrite) : undefined,
      addrs: globalThis.Array.isArray(object?.addrs) ? object.addrs.map((e: any) => globalThis.String(e)) : [],
      curAddr: isSet(object.curAddr) ? globalThis.String(object.curAddr) : undefined,
      iceAddr: isSet(object.iceAddr) ? globalThis.String(object.iceAddr) : undefined,
    };
  },

  toJSON(message: PeerStatus): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.publicKey !== "") {
      obj.publicKey = message.publicKey;
    }
    if (message.os !== "") {
      obj.os = message.os;
    }
    if (message.hostName !== "") {
      obj.hostName = message.hostName;
    }
    if (message.runetaleIps?.length) {
      obj.RunetaleIPs = message.runetaleIps;
    }
    if (message.peerApiUrl?.length) {
      obj.peerApiUrl = message.peerApiUrl;
    }
    if (message.allowedIps?.length) {
      obj.allowedIps = message.allowedIps;
    }
    if (message.rxBytes !== 0) {
      obj.rxBytes = Math.round(message.rxBytes);
    }
    if (message.txBytes !== 0) {
      obj.txBytes = Math.round(message.txBytes);
    }
    if (message.lastHandshake !== undefined) {
      obj.lastHandshake = message.lastHandshake.toISOString();
    }
    if (message.lastWrite !== undefined) {
      obj.lastWrite = message.lastWrite.toISOString();
    }
    if (message.addrs?.length) {
      obj.addrs = message.addrs;
    }
    if (message.curAddr !== undefined) {
      obj.curAddr = message.curAddr;
    }
    if (message.iceAddr !== undefined) {
      obj.iceAddr = message.iceAddr;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PeerStatus>, I>>(base?: I): PeerStatus {
    return PeerStatus.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PeerStatus>, I>>(object: I): PeerStatus {
    const message = createBasePeerStatus();
    message.id = object.id ?? 0;
    message.publicKey = object.publicKey ?? "";
    message.os = object.os ?? "";
    message.hostName = object.hostName ?? "";
    message.runetaleIps = object.runetaleIps?.map((e) => e) || [];
    message.peerApiUrl = object.peerApiUrl?.map((e) => e) || [];
    message.allowedIps = object.allowedIps?.map((e) => e) || [];
    message.rxBytes = object.rxBytes ?? 0;
    message.txBytes = object.txBytes ?? 0;
    message.lastHandshake = object.lastHandshake ?? undefined;
    message.lastWrite = object.lastWrite ?? undefined;
    message.addrs = object.addrs?.map((e) => e) || [];
    message.curAddr = object.curAddr ?? undefined;
    message.iceAddr = object.iceAddr ?? undefined;
    return message;
  },
};

function createBaseUserspacePeerEngineStatus(): UserspacePeerEngineStatus {
  return { gotAt: undefined, peers: [], localAddrs: [] };
}

export const UserspacePeerEngineStatus: MessageFns<UserspacePeerEngineStatus> = {
  encode(message: UserspacePeerEngineStatus, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.gotAt !== undefined) {
      Timestamp.encode(toTimestamp(message.gotAt), writer.uint32(10).fork()).join();
    }
    for (const v of message.peers) {
      CompactPeerStatus.encode(v!, writer.uint32(18).fork()).join();
    }
    for (const v of message.localAddrs) {
      Endpoint.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserspacePeerEngineStatus {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserspacePeerEngineStatus();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.gotAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.peers.push(CompactPeerStatus.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.localAddrs.push(Endpoint.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UserspacePeerEngineStatus {
    return {
      gotAt: isSet(object.gotAt) ? fromJsonTimestamp(object.gotAt) : undefined,
      peers: globalThis.Array.isArray(object?.peers) ? object.peers.map((e: any) => CompactPeerStatus.fromJSON(e)) : [],
      localAddrs: globalThis.Array.isArray(object?.localAddrs)
        ? object.localAddrs.map((e: any) => Endpoint.fromJSON(e))
        : [],
    };
  },

  toJSON(message: UserspacePeerEngineStatus): unknown {
    const obj: any = {};
    if (message.gotAt !== undefined) {
      obj.gotAt = message.gotAt.toISOString();
    }
    if (message.peers?.length) {
      obj.peers = message.peers.map((e) => CompactPeerStatus.toJSON(e));
    }
    if (message.localAddrs?.length) {
      obj.localAddrs = message.localAddrs.map((e) => Endpoint.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UserspacePeerEngineStatus>, I>>(base?: I): UserspacePeerEngineStatus {
    return UserspacePeerEngineStatus.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UserspacePeerEngineStatus>, I>>(object: I): UserspacePeerEngineStatus {
    const message = createBaseUserspacePeerEngineStatus();
    message.gotAt = object.gotAt ?? undefined;
    message.peers = object.peers?.map((e) => CompactPeerStatus.fromPartial(e)) || [];
    message.localAddrs = object.localAddrs?.map((e) => Endpoint.fromPartial(e)) || [];
    return message;
  },
};

function createBaseCompactPeerStatus(): CompactPeerStatus {
  return { nodeKey: "", txBytes: 0, rxBytes: 0, lastHandshake: undefined };
}

export const CompactPeerStatus: MessageFns<CompactPeerStatus> = {
  encode(message: CompactPeerStatus, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.nodeKey !== "") {
      writer.uint32(10).string(message.nodeKey);
    }
    if (message.txBytes !== 0) {
      writer.uint32(16).int64(message.txBytes);
    }
    if (message.rxBytes !== 0) {
      writer.uint32(24).int64(message.rxBytes);
    }
    if (message.lastHandshake !== undefined) {
      Timestamp.encode(toTimestamp(message.lastHandshake), writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CompactPeerStatus {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCompactPeerStatus();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.nodeKey = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.txBytes = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.rxBytes = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.lastHandshake = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CompactPeerStatus {
    return {
      nodeKey: isSet(object.nodeKey) ? globalThis.String(object.nodeKey) : "",
      txBytes: isSet(object.txBytes) ? globalThis.Number(object.txBytes) : 0,
      rxBytes: isSet(object.rxBytes) ? globalThis.Number(object.rxBytes) : 0,
      lastHandshake: isSet(object.lastHandshake) ? fromJsonTimestamp(object.lastHandshake) : undefined,
    };
  },

  toJSON(message: CompactPeerStatus): unknown {
    const obj: any = {};
    if (message.nodeKey !== "") {
      obj.nodeKey = message.nodeKey;
    }
    if (message.txBytes !== 0) {
      obj.txBytes = Math.round(message.txBytes);
    }
    if (message.rxBytes !== 0) {
      obj.rxBytes = Math.round(message.rxBytes);
    }
    if (message.lastHandshake !== undefined) {
      obj.lastHandshake = message.lastHandshake.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CompactPeerStatus>, I>>(base?: I): CompactPeerStatus {
    return CompactPeerStatus.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CompactPeerStatus>, I>>(object: I): CompactPeerStatus {
    const message = createBaseCompactPeerStatus();
    message.nodeKey = object.nodeKey ?? "";
    message.txBytes = object.txBytes ?? 0;
    message.rxBytes = object.rxBytes ?? 0;
    message.lastHandshake = object.lastHandshake ?? undefined;
    return message;
  },
};

function createBaseHashigo(): Hashigo {
  return {
    serverUrl: "",
    signalUrl: "",
    barricade: false,
    advertiseRoutes: [],
    acceptRoutes: false,
    snatSubnetRoutes: false,
    statefulFilter: false,
  };
}

export const Hashigo: MessageFns<Hashigo> = {
  encode(message: Hashigo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.serverUrl !== "") {
      writer.uint32(10).string(message.serverUrl);
    }
    if (message.signalUrl !== "") {
      writer.uint32(18).string(message.signalUrl);
    }
    if (message.barricade !== false) {
      writer.uint32(24).bool(message.barricade);
    }
    for (const v of message.advertiseRoutes) {
      writer.uint32(34).string(v!);
    }
    if (message.acceptRoutes !== false) {
      writer.uint32(40).bool(message.acceptRoutes);
    }
    if (message.snatSubnetRoutes !== false) {
      writer.uint32(48).bool(message.snatSubnetRoutes);
    }
    if (message.statefulFilter !== false) {
      writer.uint32(56).bool(message.statefulFilter);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Hashigo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHashigo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.serverUrl = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.signalUrl = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.barricade = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.advertiseRoutes.push(reader.string());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.acceptRoutes = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.snatSubnetRoutes = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.statefulFilter = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Hashigo {
    return {
      serverUrl: isSet(object.serverUrl) ? globalThis.String(object.serverUrl) : "",
      signalUrl: isSet(object.signalUrl) ? globalThis.String(object.signalUrl) : "",
      barricade: isSet(object.barricade) ? globalThis.Boolean(object.barricade) : false,
      advertiseRoutes: globalThis.Array.isArray(object?.advertiseRoutes)
        ? object.advertiseRoutes.map((e: any) => globalThis.String(e))
        : [],
      acceptRoutes: isSet(object.acceptRoutes) ? globalThis.Boolean(object.acceptRoutes) : false,
      snatSubnetRoutes: isSet(object.snatSubnetRoutes) ? globalThis.Boolean(object.snatSubnetRoutes) : false,
      statefulFilter: isSet(object.statefulFilter) ? globalThis.Boolean(object.statefulFilter) : false,
    };
  },

  toJSON(message: Hashigo): unknown {
    const obj: any = {};
    if (message.serverUrl !== "") {
      obj.serverUrl = message.serverUrl;
    }
    if (message.signalUrl !== "") {
      obj.signalUrl = message.signalUrl;
    }
    if (message.barricade !== false) {
      obj.barricade = message.barricade;
    }
    if (message.advertiseRoutes?.length) {
      obj.advertiseRoutes = message.advertiseRoutes;
    }
    if (message.acceptRoutes !== false) {
      obj.acceptRoutes = message.acceptRoutes;
    }
    if (message.snatSubnetRoutes !== false) {
      obj.snatSubnetRoutes = message.snatSubnetRoutes;
    }
    if (message.statefulFilter !== false) {
      obj.statefulFilter = message.statefulFilter;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Hashigo>, I>>(base?: I): Hashigo {
    return Hashigo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Hashigo>, I>>(object: I): Hashigo {
    const message = createBaseHashigo();
    message.serverUrl = object.serverUrl ?? "";
    message.signalUrl = object.signalUrl ?? "";
    message.barricade = object.barricade ?? false;
    message.advertiseRoutes = object.advertiseRoutes?.map((e) => e) || [];
    message.acceptRoutes = object.acceptRoutes ?? false;
    message.snatSubnetRoutes = object.snatSubnetRoutes ?? false;
    message.statefulFilter = object.statefulFilter ?? false;
    return message;
  },
};

function createBasePingResult(): PingResult {
  return {
    ip: "",
    nodeIp: "",
    nodeName: "",
    err: "",
    latencySeconds: 0,
    endpoint: "",
    peerApiPort: 0,
    peerApiUrl: "",
    isLocalIp: false,
  };
}

export const PingResult: MessageFns<PingResult> = {
  encode(message: PingResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ip !== "") {
      writer.uint32(10).string(message.ip);
    }
    if (message.nodeIp !== "") {
      writer.uint32(18).string(message.nodeIp);
    }
    if (message.nodeName !== "") {
      writer.uint32(26).string(message.nodeName);
    }
    if (message.err !== "") {
      writer.uint32(34).string(message.err);
    }
    if (message.latencySeconds !== 0) {
      writer.uint32(41).double(message.latencySeconds);
    }
    if (message.endpoint !== "") {
      writer.uint32(50).string(message.endpoint);
    }
    if (message.peerApiPort !== 0) {
      writer.uint32(56).uint32(message.peerApiPort);
    }
    if (message.peerApiUrl !== "") {
      writer.uint32(66).string(message.peerApiUrl);
    }
    if (message.isLocalIp !== false) {
      writer.uint32(72).bool(message.isLocalIp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PingResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePingResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.ip = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.nodeIp = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.nodeName = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.err = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 41) {
            break;
          }

          message.latencySeconds = reader.double();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.endpoint = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.peerApiPort = reader.uint32();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.peerApiUrl = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.isLocalIp = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PingResult {
    return {
      ip: isSet(object.ip) ? globalThis.String(object.ip) : "",
      nodeIp: isSet(object.nodeIp) ? globalThis.String(object.nodeIp) : "",
      nodeName: isSet(object.nodeName) ? globalThis.String(object.nodeName) : "",
      err: isSet(object.err) ? globalThis.String(object.err) : "",
      latencySeconds: isSet(object.latencySeconds) ? globalThis.Number(object.latencySeconds) : 0,
      endpoint: isSet(object.endpoint) ? globalThis.String(object.endpoint) : "",
      peerApiPort: isSet(object.peerApiPort) ? globalThis.Number(object.peerApiPort) : 0,
      peerApiUrl: isSet(object.peerApiUrl) ? globalThis.String(object.peerApiUrl) : "",
      isLocalIp: isSet(object.isLocalIp) ? globalThis.Boolean(object.isLocalIp) : false,
    };
  },

  toJSON(message: PingResult): unknown {
    const obj: any = {};
    if (message.ip !== "") {
      obj.ip = message.ip;
    }
    if (message.nodeIp !== "") {
      obj.nodeIp = message.nodeIp;
    }
    if (message.nodeName !== "") {
      obj.nodeName = message.nodeName;
    }
    if (message.err !== "") {
      obj.err = message.err;
    }
    if (message.latencySeconds !== 0) {
      obj.latencySeconds = message.latencySeconds;
    }
    if (message.endpoint !== "") {
      obj.endpoint = message.endpoint;
    }
    if (message.peerApiPort !== 0) {
      obj.peerApiPort = Math.round(message.peerApiPort);
    }
    if (message.peerApiUrl !== "") {
      obj.peerApiUrl = message.peerApiUrl;
    }
    if (message.isLocalIp !== false) {
      obj.isLocalIp = message.isLocalIp;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PingResult>, I>>(base?: I): PingResult {
    return PingResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PingResult>, I>>(object: I): PingResult {
    const message = createBasePingResult();
    message.ip = object.ip ?? "";
    message.nodeIp = object.nodeIp ?? "";
    message.nodeName = object.nodeName ?? "";
    message.err = object.err ?? "";
    message.latencySeconds = object.latencySeconds ?? 0;
    message.endpoint = object.endpoint ?? "";
    message.peerApiPort = object.peerApiPort ?? 0;
    message.peerApiUrl = object.peerApiUrl ?? "";
    message.isLocalIp = object.isLocalIp ?? false;
    return message;
  },
};

function createBaseComposeRequest(): ComposeRequest {
  return { key: "" };
}

export const ComposeRequest: MessageFns<ComposeRequest> = {
  encode(message: ComposeRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ComposeRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseComposeRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ComposeRequest {
    return { key: isSet(object.key) ? globalThis.String(object.key) : "" };
  },

  toJSON(message: ComposeRequest): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ComposeRequest>, I>>(base?: I): ComposeRequest {
    return ComposeRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ComposeRequest>, I>>(object: I): ComposeRequest {
    const message = createBaseComposeRequest();
    message.key = object.key ?? "";
    return message;
  },
};

function createBaseHashigoRequest(): HashigoRequest {
  return { barricadeSet: false, acceptRoutesSet: false, snatSubnetRoutesSet: false, statefulFilterSet: false };
}

export const HashigoRequest: MessageFns<HashigoRequest> = {
  encode(message: HashigoRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.barricadeSet !== false) {
      writer.uint32(16).bool(message.barricadeSet);
    }
    if (message.acceptRoutesSet !== false) {
      writer.uint32(24).bool(message.acceptRoutesSet);
    }
    if (message.snatSubnetRoutesSet !== false) {
      writer.uint32(32).bool(message.snatSubnetRoutesSet);
    }
    if (message.statefulFilterSet !== false) {
      writer.uint32(40).bool(message.statefulFilterSet);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HashigoRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHashigoRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.barricadeSet = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.acceptRoutesSet = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.snatSubnetRoutesSet = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.statefulFilterSet = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HashigoRequest {
    return {
      barricadeSet: isSet(object.barricadeSet) ? globalThis.Boolean(object.barricadeSet) : false,
      acceptRoutesSet: isSet(object.acceptRoutesSet) ? globalThis.Boolean(object.acceptRoutesSet) : false,
      snatSubnetRoutesSet: isSet(object.snatSubnetRoutesSet) ? globalThis.Boolean(object.snatSubnetRoutesSet) : false,
      statefulFilterSet: isSet(object.statefulFilterSet) ? globalThis.Boolean(object.statefulFilterSet) : false,
    };
  },

  toJSON(message: HashigoRequest): unknown {
    const obj: any = {};
    if (message.barricadeSet !== false) {
      obj.barricadeSet = message.barricadeSet;
    }
    if (message.acceptRoutesSet !== false) {
      obj.acceptRoutesSet = message.acceptRoutesSet;
    }
    if (message.snatSubnetRoutesSet !== false) {
      obj.snatSubnetRoutesSet = message.snatSubnetRoutesSet;
    }
    if (message.statefulFilterSet !== false) {
      obj.statefulFilterSet = message.statefulFilterSet;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HashigoRequest>, I>>(base?: I): HashigoRequest {
    return HashigoRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HashigoRequest>, I>>(object: I): HashigoRequest {
    const message = createBaseHashigoRequest();
    message.barricadeSet = object.barricadeSet ?? false;
    message.acceptRoutesSet = object.acceptRoutesSet ?? false;
    message.snatSubnetRoutesSet = object.snatSubnetRoutesSet ?? false;
    message.statefulFilterSet = object.statefulFilterSet ?? false;
    return message;
  },
};

/**
 * HashiServiceはRunetale Clientのバックエンド専用のAPI's
 * hashilocalbackendのgrpc serviceとして実装されます
 */
export interface HashiService {
  Status(request: DeepPartial<Empty>, metadata?: grpc.Metadata): Promise<HashiStatus>;
  Ping(request: DeepPartial<Empty>, metadata?: grpc.Metadata): Promise<PingResult>;
  Login(request: DeepPartial<Empty>, metadata?: grpc.Metadata): Promise<HashiStatus>;
  Compose(request: DeepPartial<ComposeRequest>, metadata?: grpc.Metadata): Promise<HashiStatus>;
  Logout(request: DeepPartial<Empty>, metadata?: grpc.Metadata): Promise<HashiStatus>;
  Stop(request: DeepPartial<Empty>, metadata?: grpc.Metadata): Promise<HashiStatus>;
  Dial(request: DeepPartial<Empty>, metadata?: grpc.Metadata): Promise<HashiStatus>;
  GetHashigo(request: DeepPartial<Empty>, metadata?: grpc.Metadata): Promise<Hashigo>;
  PatchHashigo(request: DeepPartial<HashigoRequest>, metadata?: grpc.Metadata): Promise<Hashigo>;
}

export class HashiServiceClientImpl implements HashiService {
  private readonly rpc: Rpc;

  constructor(rpc: Rpc) {
    this.rpc = rpc;
    this.Status = this.Status.bind(this);
    this.Ping = this.Ping.bind(this);
    this.Login = this.Login.bind(this);
    this.Compose = this.Compose.bind(this);
    this.Logout = this.Logout.bind(this);
    this.Stop = this.Stop.bind(this);
    this.Dial = this.Dial.bind(this);
    this.GetHashigo = this.GetHashigo.bind(this);
    this.PatchHashigo = this.PatchHashigo.bind(this);
  }

  Status(request: DeepPartial<Empty>, metadata?: grpc.Metadata): Promise<HashiStatus> {
    return this.rpc.unary(HashiServiceStatusDesc, Empty.fromPartial(request), metadata);
  }

  Ping(request: DeepPartial<Empty>, metadata?: grpc.Metadata): Promise<PingResult> {
    return this.rpc.unary(HashiServicePingDesc, Empty.fromPartial(request), metadata);
  }

  Login(request: DeepPartial<Empty>, metadata?: grpc.Metadata): Promise<HashiStatus> {
    return this.rpc.unary(HashiServiceLoginDesc, Empty.fromPartial(request), metadata);
  }

  Compose(request: DeepPartial<ComposeRequest>, metadata?: grpc.Metadata): Promise<HashiStatus> {
    return this.rpc.unary(HashiServiceComposeDesc, ComposeRequest.fromPartial(request), metadata);
  }

  Logout(request: DeepPartial<Empty>, metadata?: grpc.Metadata): Promise<HashiStatus> {
    return this.rpc.unary(HashiServiceLogoutDesc, Empty.fromPartial(request), metadata);
  }

  Stop(request: DeepPartial<Empty>, metadata?: grpc.Metadata): Promise<HashiStatus> {
    return this.rpc.unary(HashiServiceStopDesc, Empty.fromPartial(request), metadata);
  }

  Dial(request: DeepPartial<Empty>, metadata?: grpc.Metadata): Promise<HashiStatus> {
    return this.rpc.unary(HashiServiceDialDesc, Empty.fromPartial(request), metadata);
  }

  GetHashigo(request: DeepPartial<Empty>, metadata?: grpc.Metadata): Promise<Hashigo> {
    return this.rpc.unary(HashiServiceGetHashigoDesc, Empty.fromPartial(request), metadata);
  }

  PatchHashigo(request: DeepPartial<HashigoRequest>, metadata?: grpc.Metadata): Promise<Hashigo> {
    return this.rpc.unary(HashiServicePatchHashigoDesc, HashigoRequest.fromPartial(request), metadata);
  }
}

export const HashiServiceDesc = { serviceName: "protos.HashiService" };

export const HashiServiceStatusDesc: UnaryMethodDefinitionish = {
  methodName: "Status",
  service: HashiServiceDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return Empty.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = HashiStatus.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

export const HashiServicePingDesc: UnaryMethodDefinitionish = {
  methodName: "Ping",
  service: HashiServiceDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return Empty.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = PingResult.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

export const HashiServiceLoginDesc: UnaryMethodDefinitionish = {
  methodName: "Login",
  service: HashiServiceDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return Empty.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = HashiStatus.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

export const HashiServiceComposeDesc: UnaryMethodDefinitionish = {
  methodName: "Compose",
  service: HashiServiceDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return ComposeRequest.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = HashiStatus.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

export const HashiServiceLogoutDesc: UnaryMethodDefinitionish = {
  methodName: "Logout",
  service: HashiServiceDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return Empty.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = HashiStatus.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

export const HashiServiceStopDesc: UnaryMethodDefinitionish = {
  methodName: "Stop",
  service: HashiServiceDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return Empty.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = HashiStatus.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

export const HashiServiceDialDesc: UnaryMethodDefinitionish = {
  methodName: "Dial",
  service: HashiServiceDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return Empty.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = HashiStatus.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

export const HashiServiceGetHashigoDesc: UnaryMethodDefinitionish = {
  methodName: "GetHashigo",
  service: HashiServiceDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return Empty.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = Hashigo.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

export const HashiServicePatchHashigoDesc: UnaryMethodDefinitionish = {
  methodName: "PatchHashigo",
  service: HashiServiceDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return HashigoRequest.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = Hashigo.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

interface UnaryMethodDefinitionishR extends grpc.UnaryMethodDefinition<any, any> {
  requestStream: any;
  responseStream: any;
}

type UnaryMethodDefinitionish = UnaryMethodDefinitionishR;

interface Rpc {
  unary<T extends UnaryMethodDefinitionish>(
    methodDesc: T,
    request: any,
    metadata: grpc.Metadata | undefined,
  ): Promise<any>;
}

export class GrpcWebImpl {
  private host: string;
  private options: {
    transport?: grpc.TransportFactory;

    debug?: boolean;
    metadata?: grpc.Metadata;
    upStreamRetryCodes?: number[];
  };

  constructor(
    host: string,
    options: {
      transport?: grpc.TransportFactory;

      debug?: boolean;
      metadata?: grpc.Metadata;
      upStreamRetryCodes?: number[];
    },
  ) {
    this.host = host;
    this.options = options;
  }

  unary<T extends UnaryMethodDefinitionish>(
    methodDesc: T,
    _request: any,
    metadata: grpc.Metadata | undefined,
  ): Promise<any> {
    const request = { ..._request, ...methodDesc.requestType };
    const maybeCombinedMetadata = metadata && this.options.metadata
      ? new BrowserHeaders({ ...this.options?.metadata.headersMap, ...metadata?.headersMap })
      : metadata ?? this.options.metadata;
    return new Promise((resolve, reject) => {
      grpc.unary(methodDesc, {
        request,
        host: this.host,
        metadata: maybeCombinedMetadata ?? {},
        ...(this.options.transport !== undefined ? { transport: this.options.transport } : {}),
        debug: this.options.debug ?? false,
        onEnd: function (response) {
          if (response.status === grpc.Code.OK) {
            resolve(response.message!.toObject());
          } else {
            const err = new GrpcWebError(response.statusMessage, response.status, response.trailers);
            reject(err);
          }
        },
      });
    });
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export class GrpcWebError extends globalThis.Error {
  constructor(message: string, public code: grpc.Code, public metadata: grpc.Metadata) {
    super(message);
  }
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
