// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v3.20.3
// source: runetale/runetale/v1/log_writer.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { grpc } from "@improbable-eng/grpc-web";
import { BrowserHeaders } from "browser-headers";
import { Observable } from "rxjs";
import { share } from "rxjs/operators";
import { Timestamp } from "../../../google/protobuf/timestamp";

export const protobufPackage = "logserver";

/**
 * LoglyphUploadRequest contains a batch of client debug log entries.
 * Used inside StreamLogRequest.loglyph.
 */
export interface LoglyphUploadRequest {
  /** session_id is the ephemeral session identifier. */
  sessionId: string;
  /** client_version is the client version string. */
  clientVersion: string;
  /** entries is a list of structured log entries. */
  entries: LoglyphEntry[];
}

/** LoglyphEntry is a single client debug log entry. */
export interface LoglyphEntry {
  /** client_time is when the log was generated on the client (RFC3339Nano). */
  clientTime:
    | Date
    | undefined;
  /** level is the log level (e.g., "info", "debug", "warn", "error"). */
  level: string;
  /** text is the log message text. */
  text: string;
  /** payload is optional structured data (JSON-encoded). */
  payload: string;
  /** proc_id is the process identifier (optional). */
  procId: number;
  /** proc_seq is the process-level sequence number (optional). */
  procSeq: number;
  /** v is the verbosity level (0 = normal, 1+ = verbose). */
  v: number;
}

/**
 * LoglyphUploadResponse is returned inside StreamLogResponse.ack
 * when processing loglyph entries. Kept for structured per-type feedback.
 */
export interface LoglyphUploadResponse {
  /** accepted is the number of entries successfully stored. */
  accepted: number;
  /** dropped is the number of entries dropped. */
  dropped: number;
  /** reason is set if any entries were dropped. */
  reason: string;
}

/**
 * PacketFlowLogUploadRequest contains network flow statistics from a client.
 * Used inside StreamLogRequest.packet_flow.
 * The log server identifies the stream via log_stream_id (derived from private-id).
 *
 * Fields 8-11 embed node/tenant identity directly in the payload (A-plan).
 * This makes each log self-contained for SIEM export without requiring
 * server-side JOIN to resolve IPs to node names.
 * These values are sourced from NetworkMapResponse on the client side.
 * Older clients that don't send these fields are backward-compatible
 * (fields default to empty string, log-server stores them as-is).
 */
export interface PacketFlowLogUploadRequest {
  /** logged_at is the timestamp when the stats were collected. */
  loggedAt: string;
  /** started_at is when the measurement period started. */
  startedAt: string;
  /** ended_at is when the measurement period ended. */
  endedAt: string;
  /** peer_traffic records traffic between Runetale IPs (100.x.y.z <-> 100.x.y.z). */
  peerTraffic: PacketFlowEntry[];
  /** lan_traffic records traffic on explicitly advertised subnet routes. */
  lanTraffic: PacketFlowEntry[];
  /**
   * exit_node_traffic records exit node traffic (src is Runetale IP,
   * protocol/port/dst may be anonymized).
   */
  exitNodeTraffic: PacketFlowEntry[];
  /** transport_traffic records physical WireGuard layer traffic. */
  transportTraffic: PacketFlowEntry[];
  /**
   * telemetry_log_id is the per-node UUID assigned by runetale-server
   * (stored in nodes.telemetry_log_id, delivered via NetworkMapResponse).
   */
  telemetryLogId: string;
  /**
   * domain_telemetry_log_id is the per-tenant UUID assigned by runeauth
   * (stored in tenant_specs.domain_telemetry_log_id, delivered via NetworkMapResponse).
   */
  domainTelemetryLogId: string;
  /** node_name is the hostname of the reporting node (e.g. "alice-macbook"). */
  nodeName: string;
  /** user_email is the email of the user who owns the reporting node. */
  userEmail: string;
  /**
   * One entry per unique destination Runetale IP seen in peer_traffic entries.
   * Traffic entries reference these by matching PacketFlowEntry.dst IP prefix
   * against FlowPeerInfo.runetale_ip. This avoids duplicating node info
   * across multiple traffic entries to the same destination.
   * Only populated for peer_traffic (Runetale IP <-> Runetale IP).
   * The client resolves this from NetworkMap.PeerByRunetaleIP(dst_ip).
   */
  dstPeers: FlowPeerInfo[];
}

/**
 * FlowPeerInfo describes a peer node involved in traffic.
 * Used in PacketFlowLogUploadRequest.dst_peers:
 * node info appears once per unique destination, and PacketFlowEntry.dst IP
 * references into this list. This keeps payload size ~8% larger instead of ~57%.
 */
export interface FlowPeerInfo {
  /**
   * runetale_ip is the Runetale CGNAT IP (e.g. "100.112.0.7").
   * Used as the join key with PacketFlowEntry.dst (strip port to match).
   */
  runetaleIp: string;
  /** node_name is the hostname (e.g. "db-server.rune54494.rt.net."). */
  nodeName: string;
  /** user_email is the email of the user who owns this node. */
  userEmail: string;
  /** node_id is the telemetry_log_id UUID of the destination node. */
  nodeId: string;
}

/** PacketFlowEntry is a single 5-tuple flow record. */
export interface PacketFlowEntry {
  /** proto is the IP protocol number (6=TCP, 17=UDP, 1=ICMPv4, 58=ICMPv6). */
  proto: number;
  /** src is the source IP address. */
  src: string;
  /** dst is the destination IP address. */
  dst: string;
  /** tx_packets is the number of transmitted packets. */
  txPackets: number;
  /** tx_bytes is the number of transmitted bytes. */
  txBytes: number;
  /** rx_packets is the number of received packets. */
  rxPackets: number;
  /** rx_bytes is the number of received bytes. */
  rxBytes: number;
}

/**
 * PacketFlowLogUploadResponse is returned inside StreamLogResponse.ack
 * when processing flow logs.
 */
export interface PacketFlowLogUploadResponse {
  /** accepted is the number of flow entries successfully stored. */
  accepted: number;
}

/**
 * StreamLogRequest is sent by the client on the StreamLogs bidirectional stream.
 * Each message carries exactly one log payload via the oneof field.
 */
export interface StreamLogRequest {
  /** packet_flow carries network flow statistics (60s summaries). */
  packetFlow?:
    | PacketFlowLogUploadRequest
    | undefined;
  /** loglyph carries a batch of client debug log entries. */
  loglyph?:
    | LoglyphUploadRequest
    | undefined;
  /**
   * sequence is a client-assigned monotonically increasing number.
   * The server echoes it back in StreamAck for delivery confirmation.
   */
  sequence: number;
}

/**
 * StreamLogResponse is sent by the server on the StreamLogs bidirectional stream.
 * Each message carries either a configuration update or an acknowledgement.
 */
export interface StreamLogResponse {
  /**
   * config is a server-pushed configuration update.
   * Sent immediately on connection and whenever tenant config changes.
   */
  config?:
    | LogConfigUpdate
    | undefined;
  /** ack confirms receipt and processing of a client message. */
  ack?: StreamAck | undefined;
}

/**
 * LogConfigUpdate carries dynamic configuration from the server to the client.
 * Allows the server to adjust client logging behavior without binary updates.
 */
export interface LogConfigUpdate {
  /**
   * poll_period_seconds is the interval between flow log collections.
   * 0 means use client default (currently 60s).
   */
  pollPeriodSeconds: number;
  /**
   * min_bytes_threshold is the minimum total bytes for a connection to be logged.
   * 0 means use client default (currently 256 bytes).
   */
  minBytesThreshold: number;
  /** netflow_enabled controls whether network flow logs are collected. */
  netflowEnabled: boolean;
  /** loglyph_enabled controls whether client debug logs are collected. */
  loglyphEnabled: boolean;
}

/** StreamAck confirms that the server has received and processed a client message. */
export interface StreamAck {
  /** sequence echoes the client's StreamLogRequest.sequence. */
  sequence: number;
  /** accepted is the number of entries/events/logs successfully stored. */
  accepted: number;
  /** dropped is the number of entries/events/logs dropped (if any). */
  dropped: number;
  /** reason is set if any entries were dropped (e.g. "rate_limited", "too_large"). */
  reason: string;
}

function createBaseLoglyphUploadRequest(): LoglyphUploadRequest {
  return { sessionId: "", clientVersion: "", entries: [] };
}

export const LoglyphUploadRequest: MessageFns<LoglyphUploadRequest> = {
  encode(message: LoglyphUploadRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sessionId !== "") {
      writer.uint32(10).string(message.sessionId);
    }
    if (message.clientVersion !== "") {
      writer.uint32(18).string(message.clientVersion);
    }
    for (const v of message.entries) {
      LoglyphEntry.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LoglyphUploadRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLoglyphUploadRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sessionId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.clientVersion = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.entries.push(LoglyphEntry.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LoglyphUploadRequest {
    return {
      sessionId: isSet(object.sessionId)
        ? globalThis.String(object.sessionId)
        : isSet(object.session_id)
        ? globalThis.String(object.session_id)
        : "",
      clientVersion: isSet(object.clientVersion)
        ? globalThis.String(object.clientVersion)
        : isSet(object.client_version)
        ? globalThis.String(object.client_version)
        : "",
      entries: globalThis.Array.isArray(object?.entries)
        ? object.entries.map((e: any) => LoglyphEntry.fromJSON(e))
        : [],
    };
  },

  toJSON(message: LoglyphUploadRequest): unknown {
    const obj: any = {};
    if (message.sessionId !== "") {
      obj.sessionId = message.sessionId;
    }
    if (message.clientVersion !== "") {
      obj.clientVersion = message.clientVersion;
    }
    if (message.entries?.length) {
      obj.entries = message.entries.map((e) => LoglyphEntry.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LoglyphUploadRequest>, I>>(base?: I): LoglyphUploadRequest {
    return LoglyphUploadRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LoglyphUploadRequest>, I>>(object: I): LoglyphUploadRequest {
    const message = createBaseLoglyphUploadRequest();
    message.sessionId = object.sessionId ?? "";
    message.clientVersion = object.clientVersion ?? "";
    message.entries = object.entries?.map((e) => LoglyphEntry.fromPartial(e)) || [];
    return message;
  },
};

function createBaseLoglyphEntry(): LoglyphEntry {
  return { clientTime: undefined, level: "", text: "", payload: "", procId: 0, procSeq: 0, v: 0 };
}

export const LoglyphEntry: MessageFns<LoglyphEntry> = {
  encode(message: LoglyphEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.clientTime !== undefined) {
      Timestamp.encode(toTimestamp(message.clientTime), writer.uint32(10).fork()).join();
    }
    if (message.level !== "") {
      writer.uint32(18).string(message.level);
    }
    if (message.text !== "") {
      writer.uint32(26).string(message.text);
    }
    if (message.payload !== "") {
      writer.uint32(34).string(message.payload);
    }
    if (message.procId !== 0) {
      writer.uint32(40).uint32(message.procId);
    }
    if (message.procSeq !== 0) {
      writer.uint32(48).uint64(message.procSeq);
    }
    if (message.v !== 0) {
      writer.uint32(56).int32(message.v);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LoglyphEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLoglyphEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.clientTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.level = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.text = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.payload = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.procId = reader.uint32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.procSeq = longToNumber(reader.uint64());
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.v = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LoglyphEntry {
    return {
      clientTime: isSet(object.clientTime)
        ? fromJsonTimestamp(object.clientTime)
        : isSet(object.client_time)
        ? fromJsonTimestamp(object.client_time)
        : undefined,
      level: isSet(object.level) ? globalThis.String(object.level) : "",
      text: isSet(object.text) ? globalThis.String(object.text) : "",
      payload: isSet(object.payload) ? globalThis.String(object.payload) : "",
      procId: isSet(object.procId)
        ? globalThis.Number(object.procId)
        : isSet(object.proc_id)
        ? globalThis.Number(object.proc_id)
        : 0,
      procSeq: isSet(object.procSeq)
        ? globalThis.Number(object.procSeq)
        : isSet(object.proc_seq)
        ? globalThis.Number(object.proc_seq)
        : 0,
      v: isSet(object.v) ? globalThis.Number(object.v) : 0,
    };
  },

  toJSON(message: LoglyphEntry): unknown {
    const obj: any = {};
    if (message.clientTime !== undefined) {
      obj.clientTime = message.clientTime.toISOString();
    }
    if (message.level !== "") {
      obj.level = message.level;
    }
    if (message.text !== "") {
      obj.text = message.text;
    }
    if (message.payload !== "") {
      obj.payload = message.payload;
    }
    if (message.procId !== 0) {
      obj.procId = Math.round(message.procId);
    }
    if (message.procSeq !== 0) {
      obj.procSeq = Math.round(message.procSeq);
    }
    if (message.v !== 0) {
      obj.v = Math.round(message.v);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LoglyphEntry>, I>>(base?: I): LoglyphEntry {
    return LoglyphEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LoglyphEntry>, I>>(object: I): LoglyphEntry {
    const message = createBaseLoglyphEntry();
    message.clientTime = object.clientTime ?? undefined;
    message.level = object.level ?? "";
    message.text = object.text ?? "";
    message.payload = object.payload ?? "";
    message.procId = object.procId ?? 0;
    message.procSeq = object.procSeq ?? 0;
    message.v = object.v ?? 0;
    return message;
  },
};

function createBaseLoglyphUploadResponse(): LoglyphUploadResponse {
  return { accepted: 0, dropped: 0, reason: "" };
}

export const LoglyphUploadResponse: MessageFns<LoglyphUploadResponse> = {
  encode(message: LoglyphUploadResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.accepted !== 0) {
      writer.uint32(8).uint32(message.accepted);
    }
    if (message.dropped !== 0) {
      writer.uint32(16).uint32(message.dropped);
    }
    if (message.reason !== "") {
      writer.uint32(26).string(message.reason);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LoglyphUploadResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLoglyphUploadResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.accepted = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.dropped = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.reason = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LoglyphUploadResponse {
    return {
      accepted: isSet(object.accepted) ? globalThis.Number(object.accepted) : 0,
      dropped: isSet(object.dropped) ? globalThis.Number(object.dropped) : 0,
      reason: isSet(object.reason) ? globalThis.String(object.reason) : "",
    };
  },

  toJSON(message: LoglyphUploadResponse): unknown {
    const obj: any = {};
    if (message.accepted !== 0) {
      obj.accepted = Math.round(message.accepted);
    }
    if (message.dropped !== 0) {
      obj.dropped = Math.round(message.dropped);
    }
    if (message.reason !== "") {
      obj.reason = message.reason;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LoglyphUploadResponse>, I>>(base?: I): LoglyphUploadResponse {
    return LoglyphUploadResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LoglyphUploadResponse>, I>>(object: I): LoglyphUploadResponse {
    const message = createBaseLoglyphUploadResponse();
    message.accepted = object.accepted ?? 0;
    message.dropped = object.dropped ?? 0;
    message.reason = object.reason ?? "";
    return message;
  },
};

function createBasePacketFlowLogUploadRequest(): PacketFlowLogUploadRequest {
  return {
    loggedAt: "",
    startedAt: "",
    endedAt: "",
    peerTraffic: [],
    lanTraffic: [],
    exitNodeTraffic: [],
    transportTraffic: [],
    telemetryLogId: "",
    domainTelemetryLogId: "",
    nodeName: "",
    userEmail: "",
    dstPeers: [],
  };
}

export const PacketFlowLogUploadRequest: MessageFns<PacketFlowLogUploadRequest> = {
  encode(message: PacketFlowLogUploadRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.loggedAt !== "") {
      writer.uint32(10).string(message.loggedAt);
    }
    if (message.startedAt !== "") {
      writer.uint32(18).string(message.startedAt);
    }
    if (message.endedAt !== "") {
      writer.uint32(26).string(message.endedAt);
    }
    for (const v of message.peerTraffic) {
      PacketFlowEntry.encode(v!, writer.uint32(34).fork()).join();
    }
    for (const v of message.lanTraffic) {
      PacketFlowEntry.encode(v!, writer.uint32(42).fork()).join();
    }
    for (const v of message.exitNodeTraffic) {
      PacketFlowEntry.encode(v!, writer.uint32(50).fork()).join();
    }
    for (const v of message.transportTraffic) {
      PacketFlowEntry.encode(v!, writer.uint32(58).fork()).join();
    }
    if (message.telemetryLogId !== "") {
      writer.uint32(66).string(message.telemetryLogId);
    }
    if (message.domainTelemetryLogId !== "") {
      writer.uint32(74).string(message.domainTelemetryLogId);
    }
    if (message.nodeName !== "") {
      writer.uint32(82).string(message.nodeName);
    }
    if (message.userEmail !== "") {
      writer.uint32(90).string(message.userEmail);
    }
    for (const v of message.dstPeers) {
      FlowPeerInfo.encode(v!, writer.uint32(98).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PacketFlowLogUploadRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePacketFlowLogUploadRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.loggedAt = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.startedAt = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.endedAt = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.peerTraffic.push(PacketFlowEntry.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.lanTraffic.push(PacketFlowEntry.decode(reader, reader.uint32()));
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.exitNodeTraffic.push(PacketFlowEntry.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.transportTraffic.push(PacketFlowEntry.decode(reader, reader.uint32()));
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.telemetryLogId = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.domainTelemetryLogId = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.nodeName = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.userEmail = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.dstPeers.push(FlowPeerInfo.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PacketFlowLogUploadRequest {
    return {
      loggedAt: isSet(object.loggedAt)
        ? globalThis.String(object.loggedAt)
        : isSet(object.logged_at)
        ? globalThis.String(object.logged_at)
        : "",
      startedAt: isSet(object.startedAt)
        ? globalThis.String(object.startedAt)
        : isSet(object.started_at)
        ? globalThis.String(object.started_at)
        : "",
      endedAt: isSet(object.endedAt)
        ? globalThis.String(object.endedAt)
        : isSet(object.ended_at)
        ? globalThis.String(object.ended_at)
        : "",
      peerTraffic: globalThis.Array.isArray(object?.peerTraffic)
        ? object.peerTraffic.map((e: any) => PacketFlowEntry.fromJSON(e))
        : globalThis.Array.isArray(object?.peer_traffic)
        ? object.peer_traffic.map((e: any) => PacketFlowEntry.fromJSON(e))
        : [],
      lanTraffic: globalThis.Array.isArray(object?.lanTraffic)
        ? object.lanTraffic.map((e: any) => PacketFlowEntry.fromJSON(e))
        : globalThis.Array.isArray(object?.lan_traffic)
        ? object.lan_traffic.map((e: any) => PacketFlowEntry.fromJSON(e))
        : [],
      exitNodeTraffic: globalThis.Array.isArray(object?.exitNodeTraffic)
        ? object.exitNodeTraffic.map((e: any) => PacketFlowEntry.fromJSON(e))
        : globalThis.Array.isArray(object?.exit_node_traffic)
        ? object.exit_node_traffic.map((e: any) => PacketFlowEntry.fromJSON(e))
        : [],
      transportTraffic: globalThis.Array.isArray(object?.transportTraffic)
        ? object.transportTraffic.map((e: any) => PacketFlowEntry.fromJSON(e))
        : globalThis.Array.isArray(object?.transport_traffic)
        ? object.transport_traffic.map((e: any) => PacketFlowEntry.fromJSON(e))
        : [],
      telemetryLogId: isSet(object.telemetryLogId)
        ? globalThis.String(object.telemetryLogId)
        : isSet(object.telemetry_log_id)
        ? globalThis.String(object.telemetry_log_id)
        : "",
      domainTelemetryLogId: isSet(object.domainTelemetryLogId)
        ? globalThis.String(object.domainTelemetryLogId)
        : isSet(object.domain_telemetry_log_id)
        ? globalThis.String(object.domain_telemetry_log_id)
        : "",
      nodeName: isSet(object.nodeName)
        ? globalThis.String(object.nodeName)
        : isSet(object.node_name)
        ? globalThis.String(object.node_name)
        : "",
      userEmail: isSet(object.userEmail)
        ? globalThis.String(object.userEmail)
        : isSet(object.user_email)
        ? globalThis.String(object.user_email)
        : "",
      dstPeers: globalThis.Array.isArray(object?.dstPeers)
        ? object.dstPeers.map((e: any) => FlowPeerInfo.fromJSON(e))
        : globalThis.Array.isArray(object?.dst_peers)
        ? object.dst_peers.map((e: any) => FlowPeerInfo.fromJSON(e))
        : [],
    };
  },

  toJSON(message: PacketFlowLogUploadRequest): unknown {
    const obj: any = {};
    if (message.loggedAt !== "") {
      obj.loggedAt = message.loggedAt;
    }
    if (message.startedAt !== "") {
      obj.startedAt = message.startedAt;
    }
    if (message.endedAt !== "") {
      obj.endedAt = message.endedAt;
    }
    if (message.peerTraffic?.length) {
      obj.peerTraffic = message.peerTraffic.map((e) => PacketFlowEntry.toJSON(e));
    }
    if (message.lanTraffic?.length) {
      obj.lanTraffic = message.lanTraffic.map((e) => PacketFlowEntry.toJSON(e));
    }
    if (message.exitNodeTraffic?.length) {
      obj.exitNodeTraffic = message.exitNodeTraffic.map((e) => PacketFlowEntry.toJSON(e));
    }
    if (message.transportTraffic?.length) {
      obj.transportTraffic = message.transportTraffic.map((e) => PacketFlowEntry.toJSON(e));
    }
    if (message.telemetryLogId !== "") {
      obj.telemetryLogId = message.telemetryLogId;
    }
    if (message.domainTelemetryLogId !== "") {
      obj.domainTelemetryLogId = message.domainTelemetryLogId;
    }
    if (message.nodeName !== "") {
      obj.nodeName = message.nodeName;
    }
    if (message.userEmail !== "") {
      obj.userEmail = message.userEmail;
    }
    if (message.dstPeers?.length) {
      obj.dstPeers = message.dstPeers.map((e) => FlowPeerInfo.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PacketFlowLogUploadRequest>, I>>(base?: I): PacketFlowLogUploadRequest {
    return PacketFlowLogUploadRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PacketFlowLogUploadRequest>, I>>(object: I): PacketFlowLogUploadRequest {
    const message = createBasePacketFlowLogUploadRequest();
    message.loggedAt = object.loggedAt ?? "";
    message.startedAt = object.startedAt ?? "";
    message.endedAt = object.endedAt ?? "";
    message.peerTraffic = object.peerTraffic?.map((e) => PacketFlowEntry.fromPartial(e)) || [];
    message.lanTraffic = object.lanTraffic?.map((e) => PacketFlowEntry.fromPartial(e)) || [];
    message.exitNodeTraffic = object.exitNodeTraffic?.map((e) => PacketFlowEntry.fromPartial(e)) || [];
    message.transportTraffic = object.transportTraffic?.map((e) => PacketFlowEntry.fromPartial(e)) || [];
    message.telemetryLogId = object.telemetryLogId ?? "";
    message.domainTelemetryLogId = object.domainTelemetryLogId ?? "";
    message.nodeName = object.nodeName ?? "";
    message.userEmail = object.userEmail ?? "";
    message.dstPeers = object.dstPeers?.map((e) => FlowPeerInfo.fromPartial(e)) || [];
    return message;
  },
};

function createBaseFlowPeerInfo(): FlowPeerInfo {
  return { runetaleIp: "", nodeName: "", userEmail: "", nodeId: "" };
}

export const FlowPeerInfo: MessageFns<FlowPeerInfo> = {
  encode(message: FlowPeerInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.runetaleIp !== "") {
      writer.uint32(10).string(message.runetaleIp);
    }
    if (message.nodeName !== "") {
      writer.uint32(18).string(message.nodeName);
    }
    if (message.userEmail !== "") {
      writer.uint32(26).string(message.userEmail);
    }
    if (message.nodeId !== "") {
      writer.uint32(34).string(message.nodeId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FlowPeerInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFlowPeerInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.runetaleIp = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.nodeName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.userEmail = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.nodeId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FlowPeerInfo {
    return {
      runetaleIp: isSet(object.runetaleIp)
        ? globalThis.String(object.runetaleIp)
        : isSet(object.runetale_ip)
        ? globalThis.String(object.runetale_ip)
        : "",
      nodeName: isSet(object.nodeName)
        ? globalThis.String(object.nodeName)
        : isSet(object.node_name)
        ? globalThis.String(object.node_name)
        : "",
      userEmail: isSet(object.userEmail)
        ? globalThis.String(object.userEmail)
        : isSet(object.user_email)
        ? globalThis.String(object.user_email)
        : "",
      nodeId: isSet(object.nodeId)
        ? globalThis.String(object.nodeId)
        : isSet(object.node_id)
        ? globalThis.String(object.node_id)
        : "",
    };
  },

  toJSON(message: FlowPeerInfo): unknown {
    const obj: any = {};
    if (message.runetaleIp !== "") {
      obj.runetaleIp = message.runetaleIp;
    }
    if (message.nodeName !== "") {
      obj.nodeName = message.nodeName;
    }
    if (message.userEmail !== "") {
      obj.userEmail = message.userEmail;
    }
    if (message.nodeId !== "") {
      obj.nodeId = message.nodeId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FlowPeerInfo>, I>>(base?: I): FlowPeerInfo {
    return FlowPeerInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FlowPeerInfo>, I>>(object: I): FlowPeerInfo {
    const message = createBaseFlowPeerInfo();
    message.runetaleIp = object.runetaleIp ?? "";
    message.nodeName = object.nodeName ?? "";
    message.userEmail = object.userEmail ?? "";
    message.nodeId = object.nodeId ?? "";
    return message;
  },
};

function createBasePacketFlowEntry(): PacketFlowEntry {
  return { proto: 0, src: "", dst: "", txPackets: 0, txBytes: 0, rxPackets: 0, rxBytes: 0 };
}

export const PacketFlowEntry: MessageFns<PacketFlowEntry> = {
  encode(message: PacketFlowEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.proto !== 0) {
      writer.uint32(8).uint32(message.proto);
    }
    if (message.src !== "") {
      writer.uint32(18).string(message.src);
    }
    if (message.dst !== "") {
      writer.uint32(26).string(message.dst);
    }
    if (message.txPackets !== 0) {
      writer.uint32(32).uint64(message.txPackets);
    }
    if (message.txBytes !== 0) {
      writer.uint32(40).uint64(message.txBytes);
    }
    if (message.rxPackets !== 0) {
      writer.uint32(48).uint64(message.rxPackets);
    }
    if (message.rxBytes !== 0) {
      writer.uint32(56).uint64(message.rxBytes);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PacketFlowEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePacketFlowEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.proto = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.src = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.dst = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.txPackets = longToNumber(reader.uint64());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.txBytes = longToNumber(reader.uint64());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.rxPackets = longToNumber(reader.uint64());
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.rxBytes = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PacketFlowEntry {
    return {
      proto: isSet(object.proto) ? globalThis.Number(object.proto) : 0,
      src: isSet(object.src) ? globalThis.String(object.src) : "",
      dst: isSet(object.dst) ? globalThis.String(object.dst) : "",
      txPackets: isSet(object.txPackets)
        ? globalThis.Number(object.txPackets)
        : isSet(object.tx_packets)
        ? globalThis.Number(object.tx_packets)
        : 0,
      txBytes: isSet(object.txBytes)
        ? globalThis.Number(object.txBytes)
        : isSet(object.tx_bytes)
        ? globalThis.Number(object.tx_bytes)
        : 0,
      rxPackets: isSet(object.rxPackets)
        ? globalThis.Number(object.rxPackets)
        : isSet(object.rx_packets)
        ? globalThis.Number(object.rx_packets)
        : 0,
      rxBytes: isSet(object.rxBytes)
        ? globalThis.Number(object.rxBytes)
        : isSet(object.rx_bytes)
        ? globalThis.Number(object.rx_bytes)
        : 0,
    };
  },

  toJSON(message: PacketFlowEntry): unknown {
    const obj: any = {};
    if (message.proto !== 0) {
      obj.proto = Math.round(message.proto);
    }
    if (message.src !== "") {
      obj.src = message.src;
    }
    if (message.dst !== "") {
      obj.dst = message.dst;
    }
    if (message.txPackets !== 0) {
      obj.txPackets = Math.round(message.txPackets);
    }
    if (message.txBytes !== 0) {
      obj.txBytes = Math.round(message.txBytes);
    }
    if (message.rxPackets !== 0) {
      obj.rxPackets = Math.round(message.rxPackets);
    }
    if (message.rxBytes !== 0) {
      obj.rxBytes = Math.round(message.rxBytes);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PacketFlowEntry>, I>>(base?: I): PacketFlowEntry {
    return PacketFlowEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PacketFlowEntry>, I>>(object: I): PacketFlowEntry {
    const message = createBasePacketFlowEntry();
    message.proto = object.proto ?? 0;
    message.src = object.src ?? "";
    message.dst = object.dst ?? "";
    message.txPackets = object.txPackets ?? 0;
    message.txBytes = object.txBytes ?? 0;
    message.rxPackets = object.rxPackets ?? 0;
    message.rxBytes = object.rxBytes ?? 0;
    return message;
  },
};

function createBasePacketFlowLogUploadResponse(): PacketFlowLogUploadResponse {
  return { accepted: 0 };
}

export const PacketFlowLogUploadResponse: MessageFns<PacketFlowLogUploadResponse> = {
  encode(message: PacketFlowLogUploadResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.accepted !== 0) {
      writer.uint32(8).uint32(message.accepted);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PacketFlowLogUploadResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePacketFlowLogUploadResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.accepted = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PacketFlowLogUploadResponse {
    return { accepted: isSet(object.accepted) ? globalThis.Number(object.accepted) : 0 };
  },

  toJSON(message: PacketFlowLogUploadResponse): unknown {
    const obj: any = {};
    if (message.accepted !== 0) {
      obj.accepted = Math.round(message.accepted);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PacketFlowLogUploadResponse>, I>>(base?: I): PacketFlowLogUploadResponse {
    return PacketFlowLogUploadResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PacketFlowLogUploadResponse>, I>>(object: I): PacketFlowLogUploadResponse {
    const message = createBasePacketFlowLogUploadResponse();
    message.accepted = object.accepted ?? 0;
    return message;
  },
};

function createBaseStreamLogRequest(): StreamLogRequest {
  return { packetFlow: undefined, loglyph: undefined, sequence: 0 };
}

export const StreamLogRequest: MessageFns<StreamLogRequest> = {
  encode(message: StreamLogRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.packetFlow !== undefined) {
      PacketFlowLogUploadRequest.encode(message.packetFlow, writer.uint32(10).fork()).join();
    }
    if (message.loglyph !== undefined) {
      LoglyphUploadRequest.encode(message.loglyph, writer.uint32(26).fork()).join();
    }
    if (message.sequence !== 0) {
      writer.uint32(80).uint64(message.sequence);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StreamLogRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStreamLogRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.packetFlow = PacketFlowLogUploadRequest.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.loglyph = LoglyphUploadRequest.decode(reader, reader.uint32());
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.sequence = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StreamLogRequest {
    return {
      packetFlow: isSet(object.packetFlow)
        ? PacketFlowLogUploadRequest.fromJSON(object.packetFlow)
        : isSet(object.packet_flow)
        ? PacketFlowLogUploadRequest.fromJSON(object.packet_flow)
        : undefined,
      loglyph: isSet(object.loglyph) ? LoglyphUploadRequest.fromJSON(object.loglyph) : undefined,
      sequence: isSet(object.sequence) ? globalThis.Number(object.sequence) : 0,
    };
  },

  toJSON(message: StreamLogRequest): unknown {
    const obj: any = {};
    if (message.packetFlow !== undefined) {
      obj.packetFlow = PacketFlowLogUploadRequest.toJSON(message.packetFlow);
    }
    if (message.loglyph !== undefined) {
      obj.loglyph = LoglyphUploadRequest.toJSON(message.loglyph);
    }
    if (message.sequence !== 0) {
      obj.sequence = Math.round(message.sequence);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StreamLogRequest>, I>>(base?: I): StreamLogRequest {
    return StreamLogRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StreamLogRequest>, I>>(object: I): StreamLogRequest {
    const message = createBaseStreamLogRequest();
    message.packetFlow = (object.packetFlow !== undefined && object.packetFlow !== null)
      ? PacketFlowLogUploadRequest.fromPartial(object.packetFlow)
      : undefined;
    message.loglyph = (object.loglyph !== undefined && object.loglyph !== null)
      ? LoglyphUploadRequest.fromPartial(object.loglyph)
      : undefined;
    message.sequence = object.sequence ?? 0;
    return message;
  },
};

function createBaseStreamLogResponse(): StreamLogResponse {
  return { config: undefined, ack: undefined };
}

export const StreamLogResponse: MessageFns<StreamLogResponse> = {
  encode(message: StreamLogResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.config !== undefined) {
      LogConfigUpdate.encode(message.config, writer.uint32(10).fork()).join();
    }
    if (message.ack !== undefined) {
      StreamAck.encode(message.ack, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StreamLogResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStreamLogResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.config = LogConfigUpdate.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.ack = StreamAck.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StreamLogResponse {
    return {
      config: isSet(object.config) ? LogConfigUpdate.fromJSON(object.config) : undefined,
      ack: isSet(object.ack) ? StreamAck.fromJSON(object.ack) : undefined,
    };
  },

  toJSON(message: StreamLogResponse): unknown {
    const obj: any = {};
    if (message.config !== undefined) {
      obj.config = LogConfigUpdate.toJSON(message.config);
    }
    if (message.ack !== undefined) {
      obj.ack = StreamAck.toJSON(message.ack);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StreamLogResponse>, I>>(base?: I): StreamLogResponse {
    return StreamLogResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StreamLogResponse>, I>>(object: I): StreamLogResponse {
    const message = createBaseStreamLogResponse();
    message.config = (object.config !== undefined && object.config !== null)
      ? LogConfigUpdate.fromPartial(object.config)
      : undefined;
    message.ack = (object.ack !== undefined && object.ack !== null) ? StreamAck.fromPartial(object.ack) : undefined;
    return message;
  },
};

function createBaseLogConfigUpdate(): LogConfigUpdate {
  return { pollPeriodSeconds: 0, minBytesThreshold: 0, netflowEnabled: false, loglyphEnabled: false };
}

export const LogConfigUpdate: MessageFns<LogConfigUpdate> = {
  encode(message: LogConfigUpdate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pollPeriodSeconds !== 0) {
      writer.uint32(8).uint32(message.pollPeriodSeconds);
    }
    if (message.minBytesThreshold !== 0) {
      writer.uint32(16).uint64(message.minBytesThreshold);
    }
    if (message.netflowEnabled !== false) {
      writer.uint32(24).bool(message.netflowEnabled);
    }
    if (message.loglyphEnabled !== false) {
      writer.uint32(40).bool(message.loglyphEnabled);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LogConfigUpdate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLogConfigUpdate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.pollPeriodSeconds = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.minBytesThreshold = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.netflowEnabled = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.loglyphEnabled = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LogConfigUpdate {
    return {
      pollPeriodSeconds: isSet(object.pollPeriodSeconds)
        ? globalThis.Number(object.pollPeriodSeconds)
        : isSet(object.poll_period_seconds)
        ? globalThis.Number(object.poll_period_seconds)
        : 0,
      minBytesThreshold: isSet(object.minBytesThreshold)
        ? globalThis.Number(object.minBytesThreshold)
        : isSet(object.min_bytes_threshold)
        ? globalThis.Number(object.min_bytes_threshold)
        : 0,
      netflowEnabled: isSet(object.netflowEnabled)
        ? globalThis.Boolean(object.netflowEnabled)
        : isSet(object.netflow_enabled)
        ? globalThis.Boolean(object.netflow_enabled)
        : false,
      loglyphEnabled: isSet(object.loglyphEnabled)
        ? globalThis.Boolean(object.loglyphEnabled)
        : isSet(object.loglyph_enabled)
        ? globalThis.Boolean(object.loglyph_enabled)
        : false,
    };
  },

  toJSON(message: LogConfigUpdate): unknown {
    const obj: any = {};
    if (message.pollPeriodSeconds !== 0) {
      obj.pollPeriodSeconds = Math.round(message.pollPeriodSeconds);
    }
    if (message.minBytesThreshold !== 0) {
      obj.minBytesThreshold = Math.round(message.minBytesThreshold);
    }
    if (message.netflowEnabled !== false) {
      obj.netflowEnabled = message.netflowEnabled;
    }
    if (message.loglyphEnabled !== false) {
      obj.loglyphEnabled = message.loglyphEnabled;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LogConfigUpdate>, I>>(base?: I): LogConfigUpdate {
    return LogConfigUpdate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LogConfigUpdate>, I>>(object: I): LogConfigUpdate {
    const message = createBaseLogConfigUpdate();
    message.pollPeriodSeconds = object.pollPeriodSeconds ?? 0;
    message.minBytesThreshold = object.minBytesThreshold ?? 0;
    message.netflowEnabled = object.netflowEnabled ?? false;
    message.loglyphEnabled = object.loglyphEnabled ?? false;
    return message;
  },
};

function createBaseStreamAck(): StreamAck {
  return { sequence: 0, accepted: 0, dropped: 0, reason: "" };
}

export const StreamAck: MessageFns<StreamAck> = {
  encode(message: StreamAck, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sequence !== 0) {
      writer.uint32(8).uint64(message.sequence);
    }
    if (message.accepted !== 0) {
      writer.uint32(16).uint32(message.accepted);
    }
    if (message.dropped !== 0) {
      writer.uint32(24).uint32(message.dropped);
    }
    if (message.reason !== "") {
      writer.uint32(34).string(message.reason);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StreamAck {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStreamAck();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.sequence = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.accepted = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.dropped = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.reason = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StreamAck {
    return {
      sequence: isSet(object.sequence) ? globalThis.Number(object.sequence) : 0,
      accepted: isSet(object.accepted) ? globalThis.Number(object.accepted) : 0,
      dropped: isSet(object.dropped) ? globalThis.Number(object.dropped) : 0,
      reason: isSet(object.reason) ? globalThis.String(object.reason) : "",
    };
  },

  toJSON(message: StreamAck): unknown {
    const obj: any = {};
    if (message.sequence !== 0) {
      obj.sequence = Math.round(message.sequence);
    }
    if (message.accepted !== 0) {
      obj.accepted = Math.round(message.accepted);
    }
    if (message.dropped !== 0) {
      obj.dropped = Math.round(message.dropped);
    }
    if (message.reason !== "") {
      obj.reason = message.reason;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StreamAck>, I>>(base?: I): StreamAck {
    return StreamAck.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StreamAck>, I>>(object: I): StreamAck {
    const message = createBaseStreamAck();
    message.sequence = object.sequence ?? 0;
    message.accepted = object.accepted ?? 0;
    message.dropped = object.dropped ?? 0;
    message.reason = object.reason ?? "";
    return message;
  },
};

/**
 * LogWriterService receives log uploads from client nodes via a single
 * bidirectional stream. Two log types (Loglyph, PacketFlowLog)
 * are multiplexed over one persistent gRPC stream per client.
 *
 * Authentication: gRPC metadata "private-id" header.
 * The log server validates the format, computes log_stream_id = SHA-256(private-id),
 * and extracts optional telemetry IDs for admin correlation.
 */
export interface LogWriterService {
  /**
   * StreamLogs is a bidirectional stream for uploading all log types.
   * The client sends StreamLogRequest messages (containing one of the three
   * log payloads) and receives StreamLogResponse messages (config updates
   * and acknowledgements) from the server.
   *
   * On initial connection, the server sends a LogConfigUpdate with the
   * current configuration for this client's tenant.
   */
  StreamLogs(
    request: Observable<DeepPartial<StreamLogRequest>>,
    metadata?: grpc.Metadata,
  ): Observable<StreamLogResponse>;
}

export class LogWriterServiceClientImpl implements LogWriterService {
  private readonly rpc: Rpc;

  constructor(rpc: Rpc) {
    this.rpc = rpc;
    this.StreamLogs = this.StreamLogs.bind(this);
  }

  StreamLogs(
    request: Observable<DeepPartial<StreamLogRequest>>,
    metadata?: grpc.Metadata,
  ): Observable<StreamLogResponse> {
    throw new Error("ts-proto does not yet support client streaming!");
  }
}

export const LogWriterServiceDesc = { serviceName: "logserver.LogWriterService" };

interface UnaryMethodDefinitionishR extends grpc.UnaryMethodDefinition<any, any> {
  requestStream: any;
  responseStream: any;
}

type UnaryMethodDefinitionish = UnaryMethodDefinitionishR;

interface Rpc {
  unary<T extends UnaryMethodDefinitionish>(
    methodDesc: T,
    request: any,
    metadata: grpc.Metadata | undefined,
  ): Promise<any>;
  invoke<T extends UnaryMethodDefinitionish>(
    methodDesc: T,
    request: any,
    metadata: grpc.Metadata | undefined,
  ): Observable<any>;
}

export class GrpcWebImpl {
  private host: string;
  private options: {
    transport?: grpc.TransportFactory;
    streamingTransport?: grpc.TransportFactory;
    debug?: boolean;
    metadata?: grpc.Metadata;
    upStreamRetryCodes?: number[];
  };

  constructor(
    host: string,
    options: {
      transport?: grpc.TransportFactory;
      streamingTransport?: grpc.TransportFactory;
      debug?: boolean;
      metadata?: grpc.Metadata;
      upStreamRetryCodes?: number[];
    },
  ) {
    this.host = host;
    this.options = options;
  }

  unary<T extends UnaryMethodDefinitionish>(
    methodDesc: T,
    _request: any,
    metadata: grpc.Metadata | undefined,
  ): Promise<any> {
    const request = { ..._request, ...methodDesc.requestType };
    const maybeCombinedMetadata = metadata && this.options.metadata
      ? new BrowserHeaders({ ...this.options?.metadata.headersMap, ...metadata?.headersMap })
      : metadata ?? this.options.metadata;
    return new Promise((resolve, reject) => {
      grpc.unary(methodDesc, {
        request,
        host: this.host,
        metadata: maybeCombinedMetadata ?? {},
        ...(this.options.transport !== undefined ? { transport: this.options.transport } : {}),
        debug: this.options.debug ?? false,
        onEnd: function (response) {
          if (response.status === grpc.Code.OK) {
            resolve(response.message!.toObject());
          } else {
            const err = new GrpcWebError(response.statusMessage, response.status, response.trailers);
            reject(err);
          }
        },
      });
    });
  }

  invoke<T extends UnaryMethodDefinitionish>(
    methodDesc: T,
    _request: any,
    metadata: grpc.Metadata | undefined,
  ): Observable<any> {
    const upStreamCodes = this.options.upStreamRetryCodes ?? [];
    const DEFAULT_TIMEOUT_TIME: number = 3_000;
    const request = { ..._request, ...methodDesc.requestType };
    const transport = this.options.streamingTransport ?? this.options.transport;
    const maybeCombinedMetadata = metadata && this.options.metadata
      ? new BrowserHeaders({ ...this.options?.metadata.headersMap, ...metadata?.headersMap })
      : metadata ?? this.options.metadata;
    return new Observable((observer) => {
      const upStream = () => {
        const client = grpc.invoke(methodDesc, {
          host: this.host,
          request,
          ...(transport !== undefined ? { transport } : {}),
          metadata: maybeCombinedMetadata ?? {},
          debug: this.options.debug ?? false,
          onMessage: (next) => observer.next(next),
          onEnd: (code: grpc.Code, message: string, trailers: grpc.Metadata) => {
            if (code === 0) {
              observer.complete();
            } else if (upStreamCodes.includes(code)) {
              setTimeout(upStream, DEFAULT_TIMEOUT_TIME);
            } else {
              const err = new Error(message) as any;
              err.code = code;
              err.metadata = trailers;
              observer.error(err);
            }
          },
        });
        observer.add(() => client.close());
      };
      upStream();
    }).pipe(share());
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export class GrpcWebError extends globalThis.Error {
  constructor(message: string, public code: grpc.Code, public metadata: grpc.Metadata) {
    super(message);
  }
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
