// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v3.20.3
// source: runetale/runetale/v1/log_stats.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { grpc } from "@improbable-eng/grpc-web";
import { BrowserHeaders } from "browser-headers";
import { Timestamp } from "../../../google/protobuf/timestamp";

export const protobufPackage = "logserver";

/** GetTenantTrafficSummaryRequest queries aggregated traffic for a single tenant. */
export interface GetTenantTrafficSummaryRequest {
  /** domain_telemetry_log_id is the tenant-level telemetry ID (from tenant_specs). */
  domainTelemetryLogId: string;
  /** from is the start of the time range (inclusive). Defaults to 30 days ago if unset. */
  from:
    | Date
    | undefined;
  /** to is the end of the time range (exclusive). Defaults to now if unset. */
  to: Date | undefined;
}

/** GetTenantTrafficSummaryResponse contains the aggregated traffic for a tenant. */
export interface GetTenantTrafficSummaryResponse {
  /** domain_telemetry_log_id is the queried tenant-level telemetry ID. */
  domainTelemetryLogId: string;
  /** total_tx_bytes is the total transmitted bytes in the time range. */
  totalTxBytes: number;
  /** total_rx_bytes is the total received bytes in the time range. */
  totalRxBytes: number;
  /** total_bytes is the sum of tx + rx bytes. */
  totalBytes: number;
}

/** GetTenantTrafficSummariesRequest queries aggregated traffic for multiple tenants. */
export interface GetTenantTrafficSummariesRequest {
  /** domain_telemetry_log_ids is the list of tenant-level telemetry IDs to query. */
  domainTelemetryLogIds: string[];
  /** from is the start of the time range (inclusive). Defaults to 30 days ago if unset. */
  from:
    | Date
    | undefined;
  /** to is the end of the time range (exclusive). Defaults to now if unset. */
  to: Date | undefined;
}

/** GetTenantTrafficSummariesResponse contains the aggregated traffic for multiple tenants. */
export interface GetTenantTrafficSummariesResponse {
  /** summaries is the list of per-tenant traffic summaries. */
  summaries: TenantTrafficSummary[];
}

/** TenantTrafficSummary is the traffic summary for a single tenant. */
export interface TenantTrafficSummary {
  /** domain_telemetry_log_id is the tenant-level telemetry ID. */
  domainTelemetryLogId: string;
  /** total_tx_bytes is the total transmitted bytes in the time range. */
  totalTxBytes: number;
  /** total_rx_bytes is the total received bytes in the time range. */
  totalRxBytes: number;
  /** total_bytes is the sum of tx + rx bytes. */
  totalBytes: number;
}

function createBaseGetTenantTrafficSummaryRequest(): GetTenantTrafficSummaryRequest {
  return { domainTelemetryLogId: "", from: undefined, to: undefined };
}

export const GetTenantTrafficSummaryRequest: MessageFns<GetTenantTrafficSummaryRequest> = {
  encode(message: GetTenantTrafficSummaryRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.domainTelemetryLogId !== "") {
      writer.uint32(10).string(message.domainTelemetryLogId);
    }
    if (message.from !== undefined) {
      Timestamp.encode(toTimestamp(message.from), writer.uint32(18).fork()).join();
    }
    if (message.to !== undefined) {
      Timestamp.encode(toTimestamp(message.to), writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTenantTrafficSummaryRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTenantTrafficSummaryRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.domainTelemetryLogId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.from = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.to = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetTenantTrafficSummaryRequest {
    return {
      domainTelemetryLogId: isSet(object.domainTelemetryLogId)
        ? globalThis.String(object.domainTelemetryLogId)
        : isSet(object.domain_telemetry_log_id)
        ? globalThis.String(object.domain_telemetry_log_id)
        : "",
      from: isSet(object.from) ? fromJsonTimestamp(object.from) : undefined,
      to: isSet(object.to) ? fromJsonTimestamp(object.to) : undefined,
    };
  },

  toJSON(message: GetTenantTrafficSummaryRequest): unknown {
    const obj: any = {};
    if (message.domainTelemetryLogId !== "") {
      obj.domainTelemetryLogId = message.domainTelemetryLogId;
    }
    if (message.from !== undefined) {
      obj.from = message.from.toISOString();
    }
    if (message.to !== undefined) {
      obj.to = message.to.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetTenantTrafficSummaryRequest>, I>>(base?: I): GetTenantTrafficSummaryRequest {
    return GetTenantTrafficSummaryRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetTenantTrafficSummaryRequest>, I>>(
    object: I,
  ): GetTenantTrafficSummaryRequest {
    const message = createBaseGetTenantTrafficSummaryRequest();
    message.domainTelemetryLogId = object.domainTelemetryLogId ?? "";
    message.from = object.from ?? undefined;
    message.to = object.to ?? undefined;
    return message;
  },
};

function createBaseGetTenantTrafficSummaryResponse(): GetTenantTrafficSummaryResponse {
  return { domainTelemetryLogId: "", totalTxBytes: 0, totalRxBytes: 0, totalBytes: 0 };
}

export const GetTenantTrafficSummaryResponse: MessageFns<GetTenantTrafficSummaryResponse> = {
  encode(message: GetTenantTrafficSummaryResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.domainTelemetryLogId !== "") {
      writer.uint32(10).string(message.domainTelemetryLogId);
    }
    if (message.totalTxBytes !== 0) {
      writer.uint32(16).int64(message.totalTxBytes);
    }
    if (message.totalRxBytes !== 0) {
      writer.uint32(24).int64(message.totalRxBytes);
    }
    if (message.totalBytes !== 0) {
      writer.uint32(32).int64(message.totalBytes);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTenantTrafficSummaryResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTenantTrafficSummaryResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.domainTelemetryLogId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.totalTxBytes = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.totalRxBytes = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.totalBytes = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetTenantTrafficSummaryResponse {
    return {
      domainTelemetryLogId: isSet(object.domainTelemetryLogId)
        ? globalThis.String(object.domainTelemetryLogId)
        : isSet(object.domain_telemetry_log_id)
        ? globalThis.String(object.domain_telemetry_log_id)
        : "",
      totalTxBytes: isSet(object.totalTxBytes)
        ? globalThis.Number(object.totalTxBytes)
        : isSet(object.total_tx_bytes)
        ? globalThis.Number(object.total_tx_bytes)
        : 0,
      totalRxBytes: isSet(object.totalRxBytes)
        ? globalThis.Number(object.totalRxBytes)
        : isSet(object.total_rx_bytes)
        ? globalThis.Number(object.total_rx_bytes)
        : 0,
      totalBytes: isSet(object.totalBytes)
        ? globalThis.Number(object.totalBytes)
        : isSet(object.total_bytes)
        ? globalThis.Number(object.total_bytes)
        : 0,
    };
  },

  toJSON(message: GetTenantTrafficSummaryResponse): unknown {
    const obj: any = {};
    if (message.domainTelemetryLogId !== "") {
      obj.domainTelemetryLogId = message.domainTelemetryLogId;
    }
    if (message.totalTxBytes !== 0) {
      obj.totalTxBytes = Math.round(message.totalTxBytes);
    }
    if (message.totalRxBytes !== 0) {
      obj.totalRxBytes = Math.round(message.totalRxBytes);
    }
    if (message.totalBytes !== 0) {
      obj.totalBytes = Math.round(message.totalBytes);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetTenantTrafficSummaryResponse>, I>>(base?: I): GetTenantTrafficSummaryResponse {
    return GetTenantTrafficSummaryResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetTenantTrafficSummaryResponse>, I>>(
    object: I,
  ): GetTenantTrafficSummaryResponse {
    const message = createBaseGetTenantTrafficSummaryResponse();
    message.domainTelemetryLogId = object.domainTelemetryLogId ?? "";
    message.totalTxBytes = object.totalTxBytes ?? 0;
    message.totalRxBytes = object.totalRxBytes ?? 0;
    message.totalBytes = object.totalBytes ?? 0;
    return message;
  },
};

function createBaseGetTenantTrafficSummariesRequest(): GetTenantTrafficSummariesRequest {
  return { domainTelemetryLogIds: [], from: undefined, to: undefined };
}

export const GetTenantTrafficSummariesRequest: MessageFns<GetTenantTrafficSummariesRequest> = {
  encode(message: GetTenantTrafficSummariesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.domainTelemetryLogIds) {
      writer.uint32(10).string(v!);
    }
    if (message.from !== undefined) {
      Timestamp.encode(toTimestamp(message.from), writer.uint32(18).fork()).join();
    }
    if (message.to !== undefined) {
      Timestamp.encode(toTimestamp(message.to), writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTenantTrafficSummariesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTenantTrafficSummariesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.domainTelemetryLogIds.push(reader.string());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.from = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.to = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetTenantTrafficSummariesRequest {
    return {
      domainTelemetryLogIds: globalThis.Array.isArray(object?.domainTelemetryLogIds)
        ? object.domainTelemetryLogIds.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.domain_telemetry_log_ids)
        ? object.domain_telemetry_log_ids.map((e: any) => globalThis.String(e))
        : [],
      from: isSet(object.from) ? fromJsonTimestamp(object.from) : undefined,
      to: isSet(object.to) ? fromJsonTimestamp(object.to) : undefined,
    };
  },

  toJSON(message: GetTenantTrafficSummariesRequest): unknown {
    const obj: any = {};
    if (message.domainTelemetryLogIds?.length) {
      obj.domainTelemetryLogIds = message.domainTelemetryLogIds;
    }
    if (message.from !== undefined) {
      obj.from = message.from.toISOString();
    }
    if (message.to !== undefined) {
      obj.to = message.to.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetTenantTrafficSummariesRequest>, I>>(
    base?: I,
  ): GetTenantTrafficSummariesRequest {
    return GetTenantTrafficSummariesRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetTenantTrafficSummariesRequest>, I>>(
    object: I,
  ): GetTenantTrafficSummariesRequest {
    const message = createBaseGetTenantTrafficSummariesRequest();
    message.domainTelemetryLogIds = object.domainTelemetryLogIds?.map((e) => e) || [];
    message.from = object.from ?? undefined;
    message.to = object.to ?? undefined;
    return message;
  },
};

function createBaseGetTenantTrafficSummariesResponse(): GetTenantTrafficSummariesResponse {
  return { summaries: [] };
}

export const GetTenantTrafficSummariesResponse: MessageFns<GetTenantTrafficSummariesResponse> = {
  encode(message: GetTenantTrafficSummariesResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.summaries) {
      TenantTrafficSummary.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTenantTrafficSummariesResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTenantTrafficSummariesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.summaries.push(TenantTrafficSummary.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetTenantTrafficSummariesResponse {
    return {
      summaries: globalThis.Array.isArray(object?.summaries)
        ? object.summaries.map((e: any) => TenantTrafficSummary.fromJSON(e))
        : [],
    };
  },

  toJSON(message: GetTenantTrafficSummariesResponse): unknown {
    const obj: any = {};
    if (message.summaries?.length) {
      obj.summaries = message.summaries.map((e) => TenantTrafficSummary.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetTenantTrafficSummariesResponse>, I>>(
    base?: I,
  ): GetTenantTrafficSummariesResponse {
    return GetTenantTrafficSummariesResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetTenantTrafficSummariesResponse>, I>>(
    object: I,
  ): GetTenantTrafficSummariesResponse {
    const message = createBaseGetTenantTrafficSummariesResponse();
    message.summaries = object.summaries?.map((e) => TenantTrafficSummary.fromPartial(e)) || [];
    return message;
  },
};

function createBaseTenantTrafficSummary(): TenantTrafficSummary {
  return { domainTelemetryLogId: "", totalTxBytes: 0, totalRxBytes: 0, totalBytes: 0 };
}

export const TenantTrafficSummary: MessageFns<TenantTrafficSummary> = {
  encode(message: TenantTrafficSummary, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.domainTelemetryLogId !== "") {
      writer.uint32(10).string(message.domainTelemetryLogId);
    }
    if (message.totalTxBytes !== 0) {
      writer.uint32(16).int64(message.totalTxBytes);
    }
    if (message.totalRxBytes !== 0) {
      writer.uint32(24).int64(message.totalRxBytes);
    }
    if (message.totalBytes !== 0) {
      writer.uint32(32).int64(message.totalBytes);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TenantTrafficSummary {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTenantTrafficSummary();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.domainTelemetryLogId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.totalTxBytes = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.totalRxBytes = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.totalBytes = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TenantTrafficSummary {
    return {
      domainTelemetryLogId: isSet(object.domainTelemetryLogId)
        ? globalThis.String(object.domainTelemetryLogId)
        : isSet(object.domain_telemetry_log_id)
        ? globalThis.String(object.domain_telemetry_log_id)
        : "",
      totalTxBytes: isSet(object.totalTxBytes)
        ? globalThis.Number(object.totalTxBytes)
        : isSet(object.total_tx_bytes)
        ? globalThis.Number(object.total_tx_bytes)
        : 0,
      totalRxBytes: isSet(object.totalRxBytes)
        ? globalThis.Number(object.totalRxBytes)
        : isSet(object.total_rx_bytes)
        ? globalThis.Number(object.total_rx_bytes)
        : 0,
      totalBytes: isSet(object.totalBytes)
        ? globalThis.Number(object.totalBytes)
        : isSet(object.total_bytes)
        ? globalThis.Number(object.total_bytes)
        : 0,
    };
  },

  toJSON(message: TenantTrafficSummary): unknown {
    const obj: any = {};
    if (message.domainTelemetryLogId !== "") {
      obj.domainTelemetryLogId = message.domainTelemetryLogId;
    }
    if (message.totalTxBytes !== 0) {
      obj.totalTxBytes = Math.round(message.totalTxBytes);
    }
    if (message.totalRxBytes !== 0) {
      obj.totalRxBytes = Math.round(message.totalRxBytes);
    }
    if (message.totalBytes !== 0) {
      obj.totalBytes = Math.round(message.totalBytes);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TenantTrafficSummary>, I>>(base?: I): TenantTrafficSummary {
    return TenantTrafficSummary.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TenantTrafficSummary>, I>>(object: I): TenantTrafficSummary {
    const message = createBaseTenantTrafficSummary();
    message.domainTelemetryLogId = object.domainTelemetryLogId ?? "";
    message.totalTxBytes = object.totalTxBytes ?? 0;
    message.totalRxBytes = object.totalRxBytes ?? 0;
    message.totalBytes = object.totalBytes ?? 0;
    return message;
  },
};

/**
 * LogStatsService provides aggregated traffic statistics for MSP integrations.
 * Authentication: gRPC metadata "authorization" header with Bearer JWT token.
 * Queries are based on domain_telemetry_log_id (tenant-level identifier).
 */
export interface LogStatsService {
  /** GetTenantTrafficSummary returns aggregated traffic bytes for a single tenant. */
  GetTenantTrafficSummary(
    request: DeepPartial<GetTenantTrafficSummaryRequest>,
    metadata?: grpc.Metadata,
  ): Promise<GetTenantTrafficSummaryResponse>;
  /**
   * GetTenantTrafficSummaries returns aggregated traffic bytes for multiple tenants in one call.
   * Used by MSP to aggregate stats across parent + child tenants.
   */
  GetTenantTrafficSummaries(
    request: DeepPartial<GetTenantTrafficSummariesRequest>,
    metadata?: grpc.Metadata,
  ): Promise<GetTenantTrafficSummariesResponse>;
}

export class LogStatsServiceClientImpl implements LogStatsService {
  private readonly rpc: Rpc;

  constructor(rpc: Rpc) {
    this.rpc = rpc;
    this.GetTenantTrafficSummary = this.GetTenantTrafficSummary.bind(this);
    this.GetTenantTrafficSummaries = this.GetTenantTrafficSummaries.bind(this);
  }

  GetTenantTrafficSummary(
    request: DeepPartial<GetTenantTrafficSummaryRequest>,
    metadata?: grpc.Metadata,
  ): Promise<GetTenantTrafficSummaryResponse> {
    return this.rpc.unary(
      LogStatsServiceGetTenantTrafficSummaryDesc,
      GetTenantTrafficSummaryRequest.fromPartial(request),
      metadata,
    );
  }

  GetTenantTrafficSummaries(
    request: DeepPartial<GetTenantTrafficSummariesRequest>,
    metadata?: grpc.Metadata,
  ): Promise<GetTenantTrafficSummariesResponse> {
    return this.rpc.unary(
      LogStatsServiceGetTenantTrafficSummariesDesc,
      GetTenantTrafficSummariesRequest.fromPartial(request),
      metadata,
    );
  }
}

export const LogStatsServiceDesc = { serviceName: "logserver.LogStatsService" };

export const LogStatsServiceGetTenantTrafficSummaryDesc: UnaryMethodDefinitionish = {
  methodName: "GetTenantTrafficSummary",
  service: LogStatsServiceDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return GetTenantTrafficSummaryRequest.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = GetTenantTrafficSummaryResponse.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

export const LogStatsServiceGetTenantTrafficSummariesDesc: UnaryMethodDefinitionish = {
  methodName: "GetTenantTrafficSummaries",
  service: LogStatsServiceDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return GetTenantTrafficSummariesRequest.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = GetTenantTrafficSummariesResponse.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

interface UnaryMethodDefinitionishR extends grpc.UnaryMethodDefinition<any, any> {
  requestStream: any;
  responseStream: any;
}

type UnaryMethodDefinitionish = UnaryMethodDefinitionishR;

interface Rpc {
  unary<T extends UnaryMethodDefinitionish>(
    methodDesc: T,
    request: any,
    metadata: grpc.Metadata | undefined,
  ): Promise<any>;
}

export class GrpcWebImpl {
  private host: string;
  private options: {
    transport?: grpc.TransportFactory;

    debug?: boolean;
    metadata?: grpc.Metadata;
    upStreamRetryCodes?: number[];
  };

  constructor(
    host: string,
    options: {
      transport?: grpc.TransportFactory;

      debug?: boolean;
      metadata?: grpc.Metadata;
      upStreamRetryCodes?: number[];
    },
  ) {
    this.host = host;
    this.options = options;
  }

  unary<T extends UnaryMethodDefinitionish>(
    methodDesc: T,
    _request: any,
    metadata: grpc.Metadata | undefined,
  ): Promise<any> {
    const request = { ..._request, ...methodDesc.requestType };
    const maybeCombinedMetadata = metadata && this.options.metadata
      ? new BrowserHeaders({ ...this.options?.metadata.headersMap, ...metadata?.headersMap })
      : metadata ?? this.options.metadata;
    return new Promise((resolve, reject) => {
      grpc.unary(methodDesc, {
        request,
        host: this.host,
        metadata: maybeCombinedMetadata ?? {},
        ...(this.options.transport !== undefined ? { transport: this.options.transport } : {}),
        debug: this.options.debug ?? false,
        onEnd: function (response) {
          if (response.status === grpc.Code.OK) {
            resolve(response.message!.toObject());
          } else {
            const err = new GrpcWebError(response.statusMessage, response.status, response.trailers);
            reject(err);
          }
        },
      });
    });
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export class GrpcWebError extends globalThis.Error {
  constructor(message: string, public code: grpc.Code, public metadata: grpc.Metadata) {
    super(message);
  }
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
