// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v3.20.3
// source: runetale/runetale/v1/negotiation.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { grpc } from "@improbable-eng/grpc-web";
import { BrowserHeaders } from "browser-headers";
import { Observable } from "rxjs";
import { share } from "rxjs/operators";
import { Empty } from "../../../google/protobuf/empty";

export const protobufPackage = "protos";

export enum NegotiationType {
  OFFER = 0,
  ANSWER = 1,
  CANDIDATE = 2,
  SAYHELLO = 3,
  UNRECOGNIZED = -1,
}

export function negotiationTypeFromJSON(object: any): NegotiationType {
  switch (object) {
    case 0:
    case "OFFER":
      return NegotiationType.OFFER;
    case 1:
    case "ANSWER":
      return NegotiationType.ANSWER;
    case 2:
    case "CANDIDATE":
      return NegotiationType.CANDIDATE;
    case 3:
    case "SAYHELLO":
      return NegotiationType.SAYHELLO;
    case -1:
    case "UNRECOGNIZED":
    default:
      return NegotiationType.UNRECOGNIZED;
  }
}

export function negotiationTypeToJSON(object: NegotiationType): string {
  switch (object) {
    case NegotiationType.OFFER:
      return "OFFER";
    case NegotiationType.ANSWER:
      return "ANSWER";
    case NegotiationType.CANDIDATE:
      return "CANDIDATE";
    case NegotiationType.SAYHELLO:
      return "SAYHELLO";
    case NegotiationType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface NegotiationMessage {
  type: NegotiationType;
  /** remote node key of the Peer you want to connect to */
  dstNodeKey: string;
  dstWgPubKey: string;
  uFlag: string;
  pwd: string;
  candidate: string;
  sessionID: Uint8Array;
  fleaPacketMessage: FleaPacketMessage | undefined;
}

export interface FleaPacketMessage {
  /** "ip:port" 形式を最大8件 */
  endpoints: string[];
  /** 鮮度/デバッグ用 */
  epochTs?:
    | number
    | undefined;
  /** 重褊定 */
  dedupeId?: Uint8Array | undefined;
}

export interface HandshakeRequest {
  /** remote node key of the Peer you want to connect to */
  dstNodeKey: string;
  /** node key of the originating peer to be sent to the remote peer */
  srcNodeKey: string;
  /** wgPubKey from request node */
  wgPubKey: string;
  uFlag: string;
  pwd: string;
  sessionID: Uint8Array;
}

export interface CandidateRequest {
  /** remote node key of the Peer you want to connect to */
  dstNodeKey: string;
  /** node key of the originating peer to be sent to the remote peer */
  srcNodeKey: string;
  /** wgPubKey from request node */
  wgPubKey: string;
  candidate: string;
}

function createBaseNegotiationMessage(): NegotiationMessage {
  return {
    type: 0,
    dstNodeKey: "",
    dstWgPubKey: "",
    uFlag: "",
    pwd: "",
    candidate: "",
    sessionID: new Uint8Array(0),
    fleaPacketMessage: undefined,
  };
}

export const NegotiationMessage: MessageFns<NegotiationMessage> = {
  encode(message: NegotiationMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== 0) {
      writer.uint32(8).int32(message.type);
    }
    if (message.dstNodeKey !== "") {
      writer.uint32(18).string(message.dstNodeKey);
    }
    if (message.dstWgPubKey !== "") {
      writer.uint32(26).string(message.dstWgPubKey);
    }
    if (message.uFlag !== "") {
      writer.uint32(34).string(message.uFlag);
    }
    if (message.pwd !== "") {
      writer.uint32(42).string(message.pwd);
    }
    if (message.candidate !== "") {
      writer.uint32(50).string(message.candidate);
    }
    if (message.sessionID.length !== 0) {
      writer.uint32(58).bytes(message.sessionID);
    }
    if (message.fleaPacketMessage !== undefined) {
      FleaPacketMessage.encode(message.fleaPacketMessage, writer.uint32(66).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NegotiationMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNegotiationMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.dstNodeKey = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.dstWgPubKey = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.uFlag = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.pwd = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.candidate = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.sessionID = reader.bytes();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.fleaPacketMessage = FleaPacketMessage.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NegotiationMessage {
    return {
      type: isSet(object.type) ? negotiationTypeFromJSON(object.type) : 0,
      dstNodeKey: isSet(object.dstNodeKey) ? globalThis.String(object.dstNodeKey) : "",
      dstWgPubKey: isSet(object.dstWgPubKey) ? globalThis.String(object.dstWgPubKey) : "",
      uFlag: isSet(object.uFlag) ? globalThis.String(object.uFlag) : "",
      pwd: isSet(object.pwd) ? globalThis.String(object.pwd) : "",
      candidate: isSet(object.candidate) ? globalThis.String(object.candidate) : "",
      sessionID: isSet(object.sessionID) ? bytesFromBase64(object.sessionID) : new Uint8Array(0),
      fleaPacketMessage: isSet(object.fleaPacketMessage)
        ? FleaPacketMessage.fromJSON(object.fleaPacketMessage)
        : undefined,
    };
  },

  toJSON(message: NegotiationMessage): unknown {
    const obj: any = {};
    if (message.type !== 0) {
      obj.type = negotiationTypeToJSON(message.type);
    }
    if (message.dstNodeKey !== "") {
      obj.dstNodeKey = message.dstNodeKey;
    }
    if (message.dstWgPubKey !== "") {
      obj.dstWgPubKey = message.dstWgPubKey;
    }
    if (message.uFlag !== "") {
      obj.uFlag = message.uFlag;
    }
    if (message.pwd !== "") {
      obj.pwd = message.pwd;
    }
    if (message.candidate !== "") {
      obj.candidate = message.candidate;
    }
    if (message.sessionID.length !== 0) {
      obj.sessionID = base64FromBytes(message.sessionID);
    }
    if (message.fleaPacketMessage !== undefined) {
      obj.fleaPacketMessage = FleaPacketMessage.toJSON(message.fleaPacketMessage);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NegotiationMessage>, I>>(base?: I): NegotiationMessage {
    return NegotiationMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NegotiationMessage>, I>>(object: I): NegotiationMessage {
    const message = createBaseNegotiationMessage();
    message.type = object.type ?? 0;
    message.dstNodeKey = object.dstNodeKey ?? "";
    message.dstWgPubKey = object.dstWgPubKey ?? "";
    message.uFlag = object.uFlag ?? "";
    message.pwd = object.pwd ?? "";
    message.candidate = object.candidate ?? "";
    message.sessionID = object.sessionID ?? new Uint8Array(0);
    message.fleaPacketMessage = (object.fleaPacketMessage !== undefined && object.fleaPacketMessage !== null)
      ? FleaPacketMessage.fromPartial(object.fleaPacketMessage)
      : undefined;
    return message;
  },
};

function createBaseFleaPacketMessage(): FleaPacketMessage {
  return { endpoints: [], epochTs: undefined, dedupeId: undefined };
}

export const FleaPacketMessage: MessageFns<FleaPacketMessage> = {
  encode(message: FleaPacketMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.endpoints) {
      writer.uint32(10).string(v!);
    }
    if (message.epochTs !== undefined) {
      writer.uint32(16).uint64(message.epochTs);
    }
    if (message.dedupeId !== undefined) {
      writer.uint32(26).bytes(message.dedupeId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FleaPacketMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFleaPacketMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.endpoints.push(reader.string());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.epochTs = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.dedupeId = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FleaPacketMessage {
    return {
      endpoints: globalThis.Array.isArray(object?.endpoints)
        ? object.endpoints.map((e: any) => globalThis.String(e))
        : [],
      epochTs: isSet(object.epochTs) ? globalThis.Number(object.epochTs) : undefined,
      dedupeId: isSet(object.dedupeId) ? bytesFromBase64(object.dedupeId) : undefined,
    };
  },

  toJSON(message: FleaPacketMessage): unknown {
    const obj: any = {};
    if (message.endpoints?.length) {
      obj.endpoints = message.endpoints;
    }
    if (message.epochTs !== undefined) {
      obj.epochTs = Math.round(message.epochTs);
    }
    if (message.dedupeId !== undefined) {
      obj.dedupeId = base64FromBytes(message.dedupeId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FleaPacketMessage>, I>>(base?: I): FleaPacketMessage {
    return FleaPacketMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FleaPacketMessage>, I>>(object: I): FleaPacketMessage {
    const message = createBaseFleaPacketMessage();
    message.endpoints = object.endpoints?.map((e) => e) || [];
    message.epochTs = object.epochTs ?? undefined;
    message.dedupeId = object.dedupeId ?? undefined;
    return message;
  },
};

function createBaseHandshakeRequest(): HandshakeRequest {
  return { dstNodeKey: "", srcNodeKey: "", wgPubKey: "", uFlag: "", pwd: "", sessionID: new Uint8Array(0) };
}

export const HandshakeRequest: MessageFns<HandshakeRequest> = {
  encode(message: HandshakeRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.dstNodeKey !== "") {
      writer.uint32(10).string(message.dstNodeKey);
    }
    if (message.srcNodeKey !== "") {
      writer.uint32(18).string(message.srcNodeKey);
    }
    if (message.wgPubKey !== "") {
      writer.uint32(26).string(message.wgPubKey);
    }
    if (message.uFlag !== "") {
      writer.uint32(34).string(message.uFlag);
    }
    if (message.pwd !== "") {
      writer.uint32(42).string(message.pwd);
    }
    if (message.sessionID.length !== 0) {
      writer.uint32(50).bytes(message.sessionID);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HandshakeRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHandshakeRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.dstNodeKey = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.srcNodeKey = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.wgPubKey = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.uFlag = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.pwd = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.sessionID = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HandshakeRequest {
    return {
      dstNodeKey: isSet(object.dstNodeKey) ? globalThis.String(object.dstNodeKey) : "",
      srcNodeKey: isSet(object.srcNodeKey) ? globalThis.String(object.srcNodeKey) : "",
      wgPubKey: isSet(object.wgPubKey) ? globalThis.String(object.wgPubKey) : "",
      uFlag: isSet(object.uFlag) ? globalThis.String(object.uFlag) : "",
      pwd: isSet(object.pwd) ? globalThis.String(object.pwd) : "",
      sessionID: isSet(object.sessionID) ? bytesFromBase64(object.sessionID) : new Uint8Array(0),
    };
  },

  toJSON(message: HandshakeRequest): unknown {
    const obj: any = {};
    if (message.dstNodeKey !== "") {
      obj.dstNodeKey = message.dstNodeKey;
    }
    if (message.srcNodeKey !== "") {
      obj.srcNodeKey = message.srcNodeKey;
    }
    if (message.wgPubKey !== "") {
      obj.wgPubKey = message.wgPubKey;
    }
    if (message.uFlag !== "") {
      obj.uFlag = message.uFlag;
    }
    if (message.pwd !== "") {
      obj.pwd = message.pwd;
    }
    if (message.sessionID.length !== 0) {
      obj.sessionID = base64FromBytes(message.sessionID);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HandshakeRequest>, I>>(base?: I): HandshakeRequest {
    return HandshakeRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HandshakeRequest>, I>>(object: I): HandshakeRequest {
    const message = createBaseHandshakeRequest();
    message.dstNodeKey = object.dstNodeKey ?? "";
    message.srcNodeKey = object.srcNodeKey ?? "";
    message.wgPubKey = object.wgPubKey ?? "";
    message.uFlag = object.uFlag ?? "";
    message.pwd = object.pwd ?? "";
    message.sessionID = object.sessionID ?? new Uint8Array(0);
    return message;
  },
};

function createBaseCandidateRequest(): CandidateRequest {
  return { dstNodeKey: "", srcNodeKey: "", wgPubKey: "", candidate: "" };
}

export const CandidateRequest: MessageFns<CandidateRequest> = {
  encode(message: CandidateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.dstNodeKey !== "") {
      writer.uint32(10).string(message.dstNodeKey);
    }
    if (message.srcNodeKey !== "") {
      writer.uint32(18).string(message.srcNodeKey);
    }
    if (message.wgPubKey !== "") {
      writer.uint32(26).string(message.wgPubKey);
    }
    if (message.candidate !== "") {
      writer.uint32(34).string(message.candidate);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CandidateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCandidateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.dstNodeKey = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.srcNodeKey = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.wgPubKey = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.candidate = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CandidateRequest {
    return {
      dstNodeKey: isSet(object.dstNodeKey) ? globalThis.String(object.dstNodeKey) : "",
      srcNodeKey: isSet(object.srcNodeKey) ? globalThis.String(object.srcNodeKey) : "",
      wgPubKey: isSet(object.wgPubKey) ? globalThis.String(object.wgPubKey) : "",
      candidate: isSet(object.candidate) ? globalThis.String(object.candidate) : "",
    };
  },

  toJSON(message: CandidateRequest): unknown {
    const obj: any = {};
    if (message.dstNodeKey !== "") {
      obj.dstNodeKey = message.dstNodeKey;
    }
    if (message.srcNodeKey !== "") {
      obj.srcNodeKey = message.srcNodeKey;
    }
    if (message.wgPubKey !== "") {
      obj.wgPubKey = message.wgPubKey;
    }
    if (message.candidate !== "") {
      obj.candidate = message.candidate;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CandidateRequest>, I>>(base?: I): CandidateRequest {
    return CandidateRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CandidateRequest>, I>>(object: I): CandidateRequest {
    const message = createBaseCandidateRequest();
    message.dstNodeKey = object.dstNodeKey ?? "";
    message.srcNodeKey = object.srcNodeKey ?? "";
    message.wgPubKey = object.wgPubKey ?? "";
    message.candidate = object.candidate ?? "";
    return message;
  },
};

export interface NegotiationService {
  Offer(request: DeepPartial<HandshakeRequest>, metadata?: grpc.Metadata): Promise<Empty>;
  Answer(request: DeepPartial<HandshakeRequest>, metadata?: grpc.Metadata): Promise<Empty>;
  SayHello(request: DeepPartial<FleaPacketMessage>, metadata?: grpc.Metadata): Promise<Empty>;
  Candidate(request: DeepPartial<CandidateRequest>, metadata?: grpc.Metadata): Promise<Empty>;
  Connect(
    request: Observable<DeepPartial<NegotiationMessage>>,
    metadata?: grpc.Metadata,
  ): Observable<NegotiationMessage>;
}

export class NegotiationServiceClientImpl implements NegotiationService {
  private readonly rpc: Rpc;

  constructor(rpc: Rpc) {
    this.rpc = rpc;
    this.Offer = this.Offer.bind(this);
    this.Answer = this.Answer.bind(this);
    this.SayHello = this.SayHello.bind(this);
    this.Candidate = this.Candidate.bind(this);
    this.Connect = this.Connect.bind(this);
  }

  Offer(request: DeepPartial<HandshakeRequest>, metadata?: grpc.Metadata): Promise<Empty> {
    return this.rpc.unary(NegotiationServiceOfferDesc, HandshakeRequest.fromPartial(request), metadata);
  }

  Answer(request: DeepPartial<HandshakeRequest>, metadata?: grpc.Metadata): Promise<Empty> {
    return this.rpc.unary(NegotiationServiceAnswerDesc, HandshakeRequest.fromPartial(request), metadata);
  }

  SayHello(request: DeepPartial<FleaPacketMessage>, metadata?: grpc.Metadata): Promise<Empty> {
    return this.rpc.unary(NegotiationServiceSayHelloDesc, FleaPacketMessage.fromPartial(request), metadata);
  }

  Candidate(request: DeepPartial<CandidateRequest>, metadata?: grpc.Metadata): Promise<Empty> {
    return this.rpc.unary(NegotiationServiceCandidateDesc, CandidateRequest.fromPartial(request), metadata);
  }

  Connect(
    request: Observable<DeepPartial<NegotiationMessage>>,
    metadata?: grpc.Metadata,
  ): Observable<NegotiationMessage> {
    throw new Error("ts-proto does not yet support client streaming!");
  }
}

export const NegotiationServiceDesc = { serviceName: "protos.NegotiationService" };

export const NegotiationServiceOfferDesc: UnaryMethodDefinitionish = {
  methodName: "Offer",
  service: NegotiationServiceDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return HandshakeRequest.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = Empty.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

export const NegotiationServiceAnswerDesc: UnaryMethodDefinitionish = {
  methodName: "Answer",
  service: NegotiationServiceDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return HandshakeRequest.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = Empty.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

export const NegotiationServiceSayHelloDesc: UnaryMethodDefinitionish = {
  methodName: "SayHello",
  service: NegotiationServiceDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return FleaPacketMessage.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = Empty.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

export const NegotiationServiceCandidateDesc: UnaryMethodDefinitionish = {
  methodName: "Candidate",
  service: NegotiationServiceDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return CandidateRequest.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = Empty.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

interface UnaryMethodDefinitionishR extends grpc.UnaryMethodDefinition<any, any> {
  requestStream: any;
  responseStream: any;
}

type UnaryMethodDefinitionish = UnaryMethodDefinitionishR;

interface Rpc {
  unary<T extends UnaryMethodDefinitionish>(
    methodDesc: T,
    request: any,
    metadata: grpc.Metadata | undefined,
  ): Promise<any>;
  invoke<T extends UnaryMethodDefinitionish>(
    methodDesc: T,
    request: any,
    metadata: grpc.Metadata | undefined,
  ): Observable<any>;
}

export class GrpcWebImpl {
  private host: string;
  private options: {
    transport?: grpc.TransportFactory;
    streamingTransport?: grpc.TransportFactory;
    debug?: boolean;
    metadata?: grpc.Metadata;
    upStreamRetryCodes?: number[];
  };

  constructor(
    host: string,
    options: {
      transport?: grpc.TransportFactory;
      streamingTransport?: grpc.TransportFactory;
      debug?: boolean;
      metadata?: grpc.Metadata;
      upStreamRetryCodes?: number[];
    },
  ) {
    this.host = host;
    this.options = options;
  }

  unary<T extends UnaryMethodDefinitionish>(
    methodDesc: T,
    _request: any,
    metadata: grpc.Metadata | undefined,
  ): Promise<any> {
    const request = { ..._request, ...methodDesc.requestType };
    const maybeCombinedMetadata = metadata && this.options.metadata
      ? new BrowserHeaders({ ...this.options?.metadata.headersMap, ...metadata?.headersMap })
      : metadata ?? this.options.metadata;
    return new Promise((resolve, reject) => {
      grpc.unary(methodDesc, {
        request,
        host: this.host,
        metadata: maybeCombinedMetadata ?? {},
        ...(this.options.transport !== undefined ? { transport: this.options.transport } : {}),
        debug: this.options.debug ?? false,
        onEnd: function (response) {
          if (response.status === grpc.Code.OK) {
            resolve(response.message!.toObject());
          } else {
            const err = new GrpcWebError(response.statusMessage, response.status, response.trailers);
            reject(err);
          }
        },
      });
    });
  }

  invoke<T extends UnaryMethodDefinitionish>(
    methodDesc: T,
    _request: any,
    metadata: grpc.Metadata | undefined,
  ): Observable<any> {
    const upStreamCodes = this.options.upStreamRetryCodes ?? [];
    const DEFAULT_TIMEOUT_TIME: number = 3_000;
    const request = { ..._request, ...methodDesc.requestType };
    const transport = this.options.streamingTransport ?? this.options.transport;
    const maybeCombinedMetadata = metadata && this.options.metadata
      ? new BrowserHeaders({ ...this.options?.metadata.headersMap, ...metadata?.headersMap })
      : metadata ?? this.options.metadata;
    return new Observable((observer) => {
      const upStream = () => {
        const client = grpc.invoke(methodDesc, {
          host: this.host,
          request,
          ...(transport !== undefined ? { transport } : {}),
          metadata: maybeCombinedMetadata ?? {},
          debug: this.options.debug ?? false,
          onMessage: (next) => observer.next(next),
          onEnd: (code: grpc.Code, message: string, trailers: grpc.Metadata) => {
            if (code === 0) {
              observer.complete();
            } else if (upStreamCodes.includes(code)) {
              setTimeout(upStream, DEFAULT_TIMEOUT_TIME);
            } else {
              const err = new Error(message) as any;
              err.code = code;
              err.metadata = trailers;
              observer.error(err);
            }
          },
        });
        observer.add(() => client.close());
      };
      upStream();
    }).pipe(share());
  }
}

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export class GrpcWebError extends globalThis.Error {
  constructor(message: string, public code: grpc.Code, public metadata: grpc.Metadata) {
    super(message);
  }
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
